### ISSUE TITLE
Provide support for certificate authentication for Azure Key Vault

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.security#10]
Provide support for certificate authentication instead of basic authentication.

**Comment by tomkerkhove** [comment]
@ToonVanhoutte feel free to add the configuration suggestions you had

**Comment by ToonVanhoutte** [comment]
This feature will be very helpfull for setting up TLS mutual authentication, where the backend service wants to verify the TLS client certificate (of the API manager). Base requirement would be to validate on the thumbprint, like APIM does: <authentication-certificate thumbprint="thumbprint" />. T

his thumbprint should be configurable, preferably with an option to have it in KeyVault (with caching).

**Comment by tomkerkhove** [comment]
@ToonVanhoutte 	 I think you're more suggesting how https://github.com/arcus-azure/arcus.webapi/issues/31 should work, is that correct?

**Comment by tomkerkhove** [comment]
@arcus-azure/contributors When you would use Certificate based authentication would you prefer to:
1. Let the library handle how it should read the cert from your system?
2. Or give the `X509Certificate2` to the library which takes it from there?

When choosing for 1, where would you store it from which we get it.

**Comment by ToonVanhoutte** [comment]
Option 2 makes sense in this case, imo.

**Comment by tomkerkhove** [comment]
👌, aligns with @stijnmoreels his suggestion.

Will keep it open to gather more feedback.

**Comment by tomkerkhove** [comment]
/remind me in 4 days to proceed based on user feedback

**Comment by tomkerkhove** [comment]
X509Certificate2 it is!
