### ISSUE TITLE
Simplify package structure to make it more consumer-friendly

### ISSUE THREAD

**Issue by fgheysels** [arcus-azure/arcus.security#100]
This is not actually a feature-request, nor is it a bug.

I've seen in the code that certain types are -imho- not very well located in the source and in the namespace hierarchy.
They're rather grouped together based on their type (Interfaces, Exceptions), instead of logically grouping them together based on their functional usage.

For instance:

![image](https://user-images.githubusercontent.com/3605786/65981797-2df9cf00-e47a-11e9-9e3f-ed78604d2cab.png)
I do find it strange, that the `IKeyVaultConfiguration` interface is higher up in the namespace hierarchy then the types that implement that interface.   I would find it more natural if you 'discover' the interface first and the implementations later (or on the same level) when walking through the namespaces.  So my suggestion here would be to put the `IKeyVaultConfiguration` interface in the same namespace as its implementator `KeyVaultConfiguration` and remove the `Configuration.Interfaces` namespace altogether.  (There are various other locations in the project where I'd suggest the same approach :) ).

Something similar about exceptions that are put in an `Exceptions` namespace:  I'd put the `SecretNotFoundException` type in the `Secrets.Core` namespace and not in the `Secrets.Core.Exceptions` namespace.

Next to that, I've also seen that the `Arcus.Security.Core` assembly only contains 2 types:  `ICacheConfiguration` and `CacheConfiguration`.
My suggestion here would be that the assembly is renamed to `Arcus.Security` (or leave it like it is) and merge it with `Arcus.Security.Secrets.Core`.
That one assembly would then look like this:

```
- Arcus.Security(.Core)
-- Caching
---- Configuration
------ ICacheConfiguration.cs
------ CacheConfiguration.cs
---- ICachedSecretProvider.cs
---- CachedSecretProvider.cs
---- SecretProviderCachingExtensions.cs
-- Secret.cs
-- ISecretProvider.cs
-- SecretNotFoundException.cs
```
Then, I think I'd find it also more logical if the `KeyVaultSecretProvider` is a type that lives in the `Arcus.Security.Providers.AzureKeyVault` assembly.  There are already some KeyVault specific types in that assembly, but the `KeyVaultSecretProvider` itselfs lives on its own in a separate assembly.

So there, I'd go with something like this:

```
- Arcus.Security.Providers.AzureKeyVault
-- Authentication
---- IKeyVaultAuthentication.cs
---- CertificateBasedAuthentication.cs
---- ManagedServiceIdentityAuthentication.cs
---- ServicePrincipalAuthentication.cs
-- Configuration
---- IKeyVaultConfiguration.cs
---- ArcusConfigurationProvider.cs
---- ArcusConfigurationSource.cs
---- KeyVaultConfiguration.cs
---- SecretProviderConfigurationBuilderExtensions.cs
-- KeyVaultSecretProvider.cs
```

This is not a criticism, but rather a suggestion to have an -imho- more natural structure of the types inside the project.

**Comment by tomkerkhove** [comment]
Thanks @fgheysels, I'll have a look at them now!

**Comment by tomkerkhove** [comment]
### Key Vault & Secrets
> Then, I think I'd find it also more logical if the `KeyVaultSecretProvider` is a type that lives in the `Arcus.Security.Providers.AzureKeyVault` assembly. There are already some KeyVault specific types in that assembly, but the `KeyVaultSecretProvider` itselfs lives on its own in a separate assembly.

The reason for this is that our long-term planning is to support more than secrets and include other things like keys, crypto, certs, etc.

Given not everybody needs this we want to reduce our package(s) to only what we need so:
- `Arcus.Security.Providers.AzureKeyVault` - Provides everything in terms of general Azure Key Vault functionality, currently only auth
- `Arcus.Security.Secrets.AzureKeyVault` - Provides all things related to interacting with secrets from Key Vault, which pulls in  `Arcus.Security.Providers.AzureKeyVault`  for the auth part.

If we would support keys in Key Vault, that would end up in `Arcus.Security.Keys.AzureKeyVault` or something similar which uses `Arcus.Security.Providers.AzureKeyVault` as well.

Now that said, I've noticed that our `configurationBuilder.AddAzureKeyVault()` is part of `Arcus.Security.Providers.AzureKeyVault` which should actually be `Arcus.Security.Secrets.AzureKeyVault` given it's solely for getting secrets.

### Caching
> Next to that, I've also seen that the `Arcus.Security.Core` assembly only contains 2 types: `ICacheConfiguration` and `CacheConfiguration`.
My suggestion here would be that the assembly is renamed to `Arcus.Security` (or leave it like it is) and merge it with `Arcus.Security.Secrets.Core`.

Same thing here, they are not co-located for sake that we might need them somewhere else, but I can do see why we might want to move this now already.

This is less of a worry for me so ok with that.

### Interfaces & Exceptions
In terms of moving interfaces & exceptions - No problem and is a good suggestion.

What do you think @stijnmoreels?

**Comment by fgheysels** [comment]
> ### Key Vault & Secrets
> > Then, I think I'd find it also more logical if the `KeyVaultSecretProvider` is a type that lives in the `Arcus.Security.Providers.AzureKeyVault` assembly. There are already some KeyVault specific types in that assembly, but the `KeyVaultSecretProvider` itselfs lives on its own in a separate assembly.
> 
> The reason for this is that our long-term planning is to support more than secrets and include other things like keys, crypto, certs, etc.
> 
> Given not everybody needs this we want to reduce our package(s) to only what we need so:
> 
> * `Arcus.Security.Providers.AzureKeyVault` - Provides everything in terms of general Azure Key Vault functionality, currently only auth
> * `Arcus.Security.Secrets.AzureKeyVault` - Provides all things related to interacting with secrets from Key Vault, which pulls in  `Arcus.Security.Providers.AzureKeyVault`  for the auth part.
> 
> If we would support keys in Key Vault, that would end up in `Arcus.Security.Keys.AzureKeyVault` or something similar which uses `Arcus.Security.Providers.AzureKeyVault` as well.
>
> Now that said, I've noticed that our `configurationBuilder.AddAzureKeyVault()` is part of `Arcus.Security.Providers.AzureKeyVault` which should actually be `Arcus.Security.Secrets.AzureKeyVault` given it's solely for getting secrets.


I understand, but in that case I think you'll end up with a whole lot of small assemblies (assemblies with not much types), whereas in performance terms, it's better to load one bigger assembly instead of lots of small assemblies.
Next to that, if you need the `KeyVaultSecretProvider`, you need to pull in the `Providers.AzureKeyVault` assembly as well.   Should you also require a `KeyVaultKeysProvider`, you'll need to pull in 3 packages.

In my opinion, I would be less concerned to use one package that contains types that I do not need, instead of having to pull in multiple packages.
 
> ### Caching
> > Next to that, I've also seen that the `Arcus.Security.Core` assembly only contains 2 types: `ICacheConfiguration` and `CacheConfiguration`.
> > My suggestion here would be that the assembly is renamed to `Arcus.Security` (or leave it like it is) and merge it with `Arcus.Security.Secrets.Core`.
> 
> Same thing here, they are not co-located for sake that we might need them somewhere else, but I can do see why we might want to move this now already.
> 
> This is less of a worry for me so ok with that.
> 
> ### Interfaces & Exceptions
> In terms of moving interfaces & exceptions - No problem and is a good suggestion.
> 
> What do you think @stijnmoreels?

**Comment by fgheysels** [comment]
Today, I wanted to use the AzureKeyVault provider with caching functionality, and to be honest, I had to browse the source code to find out which package I needed to use to have the caching functionality :)

**Comment by tomkerkhove** [comment]
Agreed, will circle back  to this issue asap with an action plan!

**Comment by tomkerkhove** [comment]
Pulling in @MassimoC, @toonvanhoutte @gverstraete given they are working with Arcus as well to get some more customer feedback.

To close on the new approach I think @fgheysels his proposal sounds like a good approach so that we have following packages:
- **Arcus.Security.Core**
- **Arcus.Security.Providers.AzureKeyVault**

This would give us the following project structure:
```
- Arcus.Security(.Core)
-- Caching
---- Configuration
------ ICacheConfiguration.cs
------ CacheConfiguration.cs
---- ICachedSecretProvider.cs
---- CachedSecretProvider.cs
---- SecretProviderCachingExtensions.cs
-- Secret.cs
-- ISecretProvider.cs
-- SecretNotFoundException.cs

- **Arcus.Security.Providers.AzureKeyVault**
-- Authentication
---- IKeyVaultAuthentication.cs
---- CertificateBasedAuthentication.cs
---- ManagedServiceIdentityAuthentication.cs
---- ServicePrincipalAuthentication.cs
-- Configuration
---- IKeyVaultConfiguration.cs
---- ArcusConfigurationProvider.cs
---- ArcusConfigurationSource.cs
---- KeyVaultConfiguration.cs
---- SecretProviderConfigurationBuilderExtensions.cs
-- KeyVaultSecretProvider.cs
```

If we do this, then we'll have to:
- [ ] Update our documentation
- [ ] Change our build & release pipelines
- [ ] Change codebase
- [ ] Deprecate old packages on NuGet.org

What do you think @fgheysels @stijnmoreels?

**Comment by gverstraete** [comment]
I used to put everything in its own namespaces, so also the exceptions & the providers in this case. as it makes to me a better user friendlyness and better/easier to modify code.

So: I would keep the  **Arcus.Security.Providers.AzureKeyVault** as is, since we only have one provider class :). 

Arcus.Security(.Core) I would change to this:
```
-- Exceptions   
---- SecretNotFoundException.cs   
-- Caching   
---- Configuration   
------ ICacheConfiguration.cs   
------ CacheConfiguration.cs   
---- Providers   
------ ICachedSecretProvider.cs  
------ CachedSecretProvider.cs   
------ SecretProviderCachingExtensions.cs   
-- Secret.cs   
-- ISecretProvider.cs  
```

**Comment by tomkerkhove** [comment]
Bringing this back alive.

So we have a consensus on **Arcus.Security.Providers.AzureKeyVault**, but @gverstraete suggests a different approach for **Arcus.Security(.Core)** - Is that correct summary?

I'm fine with both approaches, but thinks that @fgheysels is not a fan of the proposed change by @gverstraete which is why this issue was created, no? I personally use Gillian his approach but I'm no expert.

**Comment by stijnmoreels** [comment]
I favor @fgheysels his approach; (as explained previously why).  Not sure how to go from here.

**Comment by tomkerkhove** [comment]
Let's use that approach then - Are you up for making these changes @stijnmoreels ?

**Comment by stijnmoreels** [comment]
> Change our build & release pipelines

Not sure what would have to change here?

**Comment by tomkerkhove** [comment]
Make sure everything still builds fine etc, but think it's ok.

**Comment by stijnmoreels** [comment]
Released v1.0.0

**Comment by tomkerkhove** [comment]
Now available in https://github.com/arcus-azure/arcus.security/releases/tag/v1.0.0, thanks @stijnmoreels!

**Comment by tomkerkhove** [comment]
Great minds think alike 😎

**Comment by stijnmoreels** [comment]
> Now available in https://github.com/arcus-azure/arcus.security/releases/tag/v1.0.0, thanks @stijnmoreels!

Should we unlist previous packages @tomkerkhove ? Like you mentioned in a previous comment?

**Comment by tomkerkhove** [comment]
Not sure what comment you are referring to? 🤔 

We shouldn't remove any NuGet packages or we will break existing customers, but we should deprecate the old ones.

This should be correct AFAIK:
- `Arcus.Security.Secrets.Core` -> `Arcus.Security.Core`
- `Arcus.Security.Secrets.AzureKeyVault` -> `Arcus.Security.Providers.AzureKeyVault`

Can you confirm @stijnmoreels ?

**Comment by tomkerkhove** [comment]
@stijnmoreels approved my suggestions and packages have been deprecated:
![image](https://user-images.githubusercontent.com/4345663/69711212-f4071b00-1100-11ea-9c64-e1b5540d6732.png)

![image](https://user-images.githubusercontent.com/4345663/69711198-ed78a380-1100-11ea-85d8-edac132893c3.png)
