### ISSUE TITLE
Should we merge SecretProvider & CachedSecretProvider?

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.security#103]
**Is your feature request related to a problem? Please describe.**
No, just a suggestion by @fgheysels 

**Describe the solution you'd like**
Merge SecretProvider & CachedSecretProvider so that we only have one secret provider which stimulates to use caching.

However, the configuration of the secret provider should allow you to opt-out of any caching.

**Describe alternatives you've considered**
Stick with the approach that we have to be more explicit in what the roles that they are.

**Additional Context**
`ICachedSecretProvider` provides a method to get the secret without checking the cache

**Comment by fgheysels** [comment]
In an afterthought, I think it might indeed be better to not merge the `ISecretProvider` and `ICachedSecretProvider`.

However, to make the cached secret provider easier to detect by a developer and use it we could create a fluent interface like this:

```csharp
ISecretProvider provider = KeyVaultProvider.Create(authentication, configuration);

ICachedSecretProvider cachingProvider = provider.WithCaching(cachingOptions);
```

This has offcourse a serious drawback: since factory methods are used, you have breaking changes.

**Comment by tomkerkhove** [comment]
We already have that as well indeed! Any tweaks we could do to help? Improve the docs then maybe?

Thanks for checking.

**Comment by fgheysels** [comment]
Might indeed be helpful if we use the extension method in the docs (if that 's not the case).  I'll have a look at it.

**Comment by tomkerkhove** [comment]
Thanks @fgheysels !

**Comment by tomkerkhove** [comment]
It's documented here https://security.arcus-azure.net/features/secrets/general#caching-secrets

Good enough for you?

**Comment by fgheysels** [comment]
> It's documented here https://security.arcus-azure.net/features/secrets/general#caching-secrets
> 
> Good enough for you?

Yes.  But I've also modified the documentation on the IConfiguration integration so that the fluent approach is displayed there as well.  (see [this](https://github.com/arcus-azure/arcus.security/pull/109) pr)

**Comment by tomkerkhove** [comment]
Merged, good addition.

Can we close this issue?

**Comment by fgheysels** [comment]
> Can we close this issue?
Yes.
