### ISSUE TITLE
Provide capability to override Key Vault provider

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.security#126]
**Is your feature request related to a problem? Please describe.**
Provide capability to override Key Vault secret provider to extend functionality.

**Comment by stijnmoreels** [comment]
What do you see useful for overriding? Authorizing the Key Vault client? Throttling logic? Exception handling during authorization and/or secret retrieval?

**Comment by tomkerkhove** [comment]
I forgot the scenario but I wanted to extend the current on; think for example logging the secret that was being called, dependency tracking, etc.

Just opening it up for others to extend where they want :)

**Comment by stijnmoreels** [comment]
So like, making the `KeyVaultSecretProvider.GetSecretAsync` `virtual`?

**Comment by tomkerkhove** [comment]
GetSecret and GetRawSecret indeed!
