### ISSUE TITLE
Provide capability to mutate secret names before looking them up

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.security#146]
**Is your feature request related to a problem? Please describe.**
Provide the capability to mutate secret names before looking them up.

This is important because now we have multiple providers and some might use a different approach.

For example, with Azure Key Vault we tend to use `API-Key` while our environment variables use `API_URL` notations. If we were to look for a secret and we provide `API-Key` it should lookup `API_Key`.

**Describe the solution you'd like**
Be able to opt-in to influence the secret names by providing a lambda.

Here is an example for environment variables:
```
builder.AddEnvironmentVariables(originalSecretName => originalSecretName.Replace("-", "_"));
```

But ideally every provider that we have now supports this because IConfiguration should use `api:key` instead of `API-KEY`

**Describe alternatives you've considered**
Every provider does this for you but this is more tricky since the convention depends on the customer. A "seperator" could be configured like this:
```
builder.AddEnvironmentVariables(keySeperator: "-");
```

But I'm not sure if that's what we prefer.

**Comment by tomkerkhove** [comment]
Thoughts @gverstraete @fgheysels @stijnmoreels ?

**Comment by stijnmoreels** [comment]
Hmm, it may leak some information on how the secret names are structured, no?

**Comment by tomkerkhove** [comment]
What scenario are you talking about or in general?

I think we have to do something because now I'm forced to use the same naming convention across all providers which doesn't really make sense, but it might just be me.

**Comment by gverstraete** [comment]
I usually tend to keep the same secret names over the whole application (except for the the Variable Group in Devops as I see this more as business oriented). So I don't see an actual use case for this at the moment.

**Comment by tomkerkhove** [comment]
So your environment variables have different naming convention for the  non secrets then or not?

**Comment by gverstraete** [comment]
No; I don't really get your point. You have sometimes the scenario where you use the same variable name for secrets and non secrets? - Can you give an example?

**Comment by tomkerkhove** [comment]
Our naming conventions are different:
- Environment Variables: `MY_ENV_VAR`
- Key Vault: `My-Secret`

**Comment by fgheysels** [comment]
I think the point is that you want to retrieve a secret in such a fashion that the developer doesn't need to worry on how the name of the secret is structured by the secret store.

For instance, you want to retrieve a secret like this:
`` 
GetSecret(secretName: "ConnectionStrings:MyDatabase");
```

However, in KeyVault the secret will be named `ConnectionStrings--MyDatabase` and when it is stored in an env variable, it will be named `ConnectionStrings__MyDatabase`.   Is that the case ?
Then, I'd assume that it is the responsability of the SecretProvider to make sure that `ConnectionStrings:MyDatabase` is correctly translated to the expected string ?

(Or am I missing the point here ? )

**Comment by tomkerkhove** [comment]
> I think the point is that you want to retrieve a secret in such a fashion that the developer doesn't need to worry on how the name of the secret is structured by the secret store.

This is definitely the case so your understanding is correct!

> However, in KeyVault the secret will be named `ConnectionStrings--MyDatabase` and when it is stored in an env variable, it will be named `ConnectionStrings__MyDatabase`. Is that the case ?
> Then, I'd assume that it is the responsability of the SecretProvider to make sure that `ConnectionStrings:MyDatabase` is correctly translated to the expected string ?
> 
> (Or am I missing the point here ? )

You are correct but I think `:` might be a special case because that's a common practice for configuration, but what if our naming convention is not to use `-` in Key Vault but use `ConnectionStringsMyDatabase` instead?

I don't think it will be used by everybody but it can certainly happen, if you have a fixed prefix or so that you need to add.

**Comment by tomkerkhove** [comment]
@stijnmoreels I presume we don't do the `:` to `--` for Key Vault, right?

**Comment by stijnmoreels** [comment]
> @stijnmoreels I presume we don't do the `:` to `--` for Key Vault yet, right?

No, nothing of the sort is implemented. 
And to come back on my very first initial comment on this: what I meant was that if we would have such functionality, that unnecessary allows devs to leak structure of secret names to the public. Maybe worse if it's badly done.

**Comment by tomkerkhove** [comment]
Well in some cases you have to have it to align with company standards/integrate with other teams. If company policy is to prefix every secret with `ARCUS-` there is nothing you can do about it; but at least you don't have it duplicated for every secret call since that would break other providers

**Comment by stijnmoreels** [comment]
> @stijnmoreels I presume we don't do the `:` to `--` for Key Vault yet, right?

And could we maybe come up with a centralized structure to call secrets but the provider registration that allows you to choose how to go from that centralized structure to the specifics?

**Comment by tomkerkhove** [comment]
I don't have a preference on that, to me that's the old way of working with secrets by using a configuration background but it might be just me.

I never use the `foo:bar` notation.

**Comment by stijnmoreels** [comment]
Is it an option to come to a 'common' secret name structure, like we make sure every secret name is seperated with a dot `.`, and we make sure that the existing and custom providers have the possibility to conform this 'common' structure?

**Comment by tomkerkhove** [comment]
Frankly, I would not enforce or push towards a pattern to follow.

I would act as a pass-through and just lookup what they provide us; but give the option to allow them to define how secret names should be mutated on a per-provider basis.
