### ISSUE TITLE
Secret Provider for ASP.NET SecretManager

### ISSUE THREAD

**Issue by fgheysels** [arcus-azure/arcus.security#152]
**What secret store are you interested in?**
A Secret Provider for the ASP.NET Secret Manager.

**What scenarios would it enable you?**

In ASP.NET, there exists a secret manager which can be used to store secrets while developing.  
Normally, this secret manager is added as a configuration provider, but if you want to separate secrets from config, I think Arcus should provide  Secret Provider for the asp.net secret manager.

**More information**
More information regarding the secret provider and how it works can be found [here](https://docs.microsoft.com/en-us/aspnet/core/security/app-secrets?view=aspnetcore-3.1&tabs=windows#secret-manager)

**Comment by tomkerkhove** [comment]
That's a good suggestion, thanks!

**Comment by stijnmoreels** [comment]
Will require `Microsoft.Extensions.Configuration.UserSecrets` to have access to the `UserSecretsIdAttribute`.
Or... we create that one ourselves and place it in our `Arcus.Secret.Core` library.
Or... we create a separate library where we add the NuGet package.

Any thoughts? @fgheysels @tomkerkhove  @gverstraete

**Comment by tomkerkhove** [comment]
We should not create it ourselves so a separate one is ok for me. I think for majority we should go with separate packages like we have for Key Vault.

**Comment by stijnmoreels** [comment]
Yes, let's go for that. Now that I'm implementing it, it seems even more logic.
