### ISSUE TITLE
Provide support for Secret Store in Azure Functions

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.security#153]
**Is your feature request related to a problem? Please describe.**
Provide support for Secret Store in Azure Functions by providing our extensions on the IFunctionHostBuilder.

**Comment by stijnmoreels** [comment]
Different library maybe? I may not want to pull in Azure Functions extensions everywhere.

**Comment by tomkerkhove** [comment]
Sure.

**Comment by stijnmoreels** [comment]
@tomkerkhove , should this new project also be referenced in the `Arcus.Security.All` project?

**Comment by tomkerkhove** [comment]
I'd say yes, all our packages should be pulled in since it's a metapackage to pull in all our packages
