### ISSUE TITLE
Provide HashiCorp Vault secret provider

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.security#159]
**Is your feature request related to a problem? Please describe.**
Provide HashiCorp Vault secret provider

**Comment by stijnmoreels** [comment]
An instance of HashiCorp can be created for this to test?

**Comment by tomkerkhove** [comment]
Yes but you have to follow this approach: https://learn.hashicorp.com/vault/getting-started/install

Once we have the integration it will be important to check how it works with Kubernetes as they recommend using CSI or sidecar over there, but let's park that for now and integrate with the vault directly for now.

**Comment by stijnmoreels** [comment]
Maybe we can build on top of this: https://github.com/rajanadar/VaultSharp

**Comment by tomkerkhove** [comment]
Sounds good, I think having basic & Kubernetes auth are least minimum required

**Comment by stijnmoreels** [comment]
> Sounds good, I think having basic & Kubernetes auth are least minimum required

Coming up!

**Comment by stijnmoreels** [comment]
Update: provider with UserPass and Kubernetes authentication. Integration test for UserPass is done, now Kubernetes is the next.

**Comment by stijnmoreels** [comment]
Closing in favor of #173 .

**Comment by tomkerkhove** [comment]
Can we add a link to this new secret provider on https://security.arcus-azure.net/preview/ please?
