### ISSUE TITLE
Suggestion - categorize allowed secret name structure

### ISSUE THREAD

**Issue by stijnmoreels** [arcus-azure/arcus.security#167]
**What secret store are you interested in?**
A `ISecretProvider` implementation that would work as an extra proxy (like the caching, user chooses where) that would make sure that (for example) only secrets that starts with the prefix `"ARCUS_"` can be looked up.
Aside from the added security perspective, this could also lead to less malicious requests to the store.

**What scenarios would it enable you?**
Anywhere where we may not have full control over the vault/store where the concrete secret provider is used.

**Comment by tomkerkhove** [comment]
Wouldn't that be already possible with the mutation & prefix?

**Comment by stijnmoreels** [comment]
> Wouldn't that be already possible with the mutation & prefix?

Not exactly. It's true the that upcoming mutation in the open PR will make sure that some structure is added or uphold, but it doesn't block secret names, only tries to change them. If we change dots `.` to underscores `_` but the malicious secret name has no dots `.`, the mutation isn't going to block that one.

**Comment by tomkerkhove** [comment]
And what would you propose then? THat it throws an exception?

But since it's most likely the same person who sets up the store who will be consuming it as well; how will we make sure they don't change the setup? SHouldn't we rely on the secret stores to have that logic?

**Comment by stijnmoreels** [comment]
The purpose here would be for me that we can limit the secret provider abilities, safe calls...

Since we don't use an result type here, yes, an exception is probably the awnser.

About the setting up an consuming... We don't know that, do we? We could just get access to some store of them, right? And/or managed outside out scope?

And yes, of course the stores themselves should have some authorization about who can access what secrets... Maybe I'm just paranoid and would add extra walls nonetheless. Fail fast if we find anything out of the ordinary.

**Comment by stijnmoreels** [comment]
Is this something that you find yourself in our should we close this.

**Comment by tomkerkhove** [comment]
Let's discuss this in person.

**Comment by stijnmoreels** [comment]
Close in favor of https://github.com/arcus-azure/arcus.security/discussions/244
