### ISSUE TITLE
Authorization issues for Azure Key Vault should not throw SecretNotFoundException

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.security#170]
Authorization issues for Azure Key Vault should not throw SecretNotFoundException.

Initially reported by @MarkLFT in https://github.com/arcus-azure/arcus.security/issues/169#issuecomment-680561430

**Comment by stijnmoreels** [comment]
What I got so far:
- When authenticating with ServicePrincipal and both user and pass is wrong: `throws Active Directory exception with 400 BadRequest`
- When authenticating with ServicePrincipal and only pass is wrong: `throws Active Directory exception with 401 Unauthorized`
- When authenticating with ServicePrincipal and usser and pass is correct but doesn't have access: `throws Key Vault exception with 403 Forbidden`

**Comment by stijnmoreels** [comment]
So, ... I guess that's all correct. 😅 .

**Comment by stijnmoreels** [comment]
What I'm thinking is that it may be an other version, but the oldest version I found here already used the same implementation that triggered my results above.

**Comment by stijnmoreels** [comment]
What it could mean, is that the secret store, the `CompositeSecretProvider` catches this, and looks for another provider that doesn't throw. Leading eventually to a 'secret not found' exception.

**Comment by tomkerkhove** [comment]
Hm, one could argue that unauthentication exceptions should be bubbled all the way up, no? And we only throw the secret not found if no exceptions were thrown as well.

**Comment by stijnmoreels** [comment]
> Hm, one could argue that unauthentication exceptions should be bubbled all the way up, no? And we only throw the secret not found if no exceptions were thrown as well.

Hmm, but what if two different unauthentication exceptions are thrown, or an unauthenticated and a secret not found (from the provider). Would you stop the lookup if 1 provider fails? Shouldn't you look at all of them first?

**Comment by tomkerkhove** [comment]
I would throw an aggregate exception with the auth issues in it; the setup is not correct so I think that's fair to do.

**Comment by tomkerkhove** [comment]
If they have different exceptions we can use an exception of our own to wrap it in or one in framework but prefer not to overkill it

**Comment by stijnmoreels** [comment]
Yeah, was Just thinking about the aggregated exception. Maybe we can collect exceptiona while going through th providers and throw an aggregated if there were any (or any authenticated-like, or other 'setup' like).
Something you can agree on?

**Comment by tomkerkhove** [comment]
Jup!

**Comment by stijnmoreels** [comment]
> Jup!

Maybe we can even make these type of exceptions configurable so people can provide additional exceptions that would make the secret store behave like that.

**Comment by tomkerkhove** [comment]
Fine by me!

**Comment by tomkerkhove** [comment]
Maybe make it optional though

**Comment by stijnmoreels** [comment]
> Maybe make it optional though

I'ts gonna be great!😉
