### ISSUE TITLE
Question - is it right that the `CachedSecretProvider` never calls the `.GetRawSecretAsync`?

### ISSUE THREAD

**Issue by stijnmoreels** [arcus-azure/arcus.security#176]
**Description**
Just saw that the `CachedSecretProvider` never calls the `.GetRawSecretAsync` on the _inner_ `ISecretProvider`. It delegates to the `.GetSecretAsync` so the wrapped provider will never be called on the raw variant.

Is that right? As I see it, I don't think that correct, but on the other hand, the cache on the `CachedSecretProvider` works with _full_ `Secret` instances so an update of the cache after calling a 'raw' variant isn't possible(?).

[Here's](https://github.com/arcus-azure/arcus.security/blob/7131882be7c1d4828b9296930c24a29ea590c1eb/src/Arcus.Security.Core/Caching/CachedSecretProvider.cs#L97) the place that I'm talking about.

**Comment by tomkerkhove** [comment]
I think that's fair because otherwise, you'll cache duplicate data. In the end, GetSecret will/should have the same value as raw secret.

**Comment by stijnmoreels** [comment]
I'll close this one as it's supposed to be the same call.
