### ISSUE TITLE
Log security event when requesting secret with `Arcus.Observability.Telemetry.Core` package once SQL package is removed

### ISSUE THREAD

**Issue by stijnmoreels** [arcus-azure/arcus.security#177]
**Is your feature request related to a problem? Please describe.**
When the `CompositeSecretProvider` request a secret (via looking it up with the registered secret provider sources), we should log this as a security event with the `Arcus.Observability.Telemtry.Core` package since this is something we should filter upon when looking for security-related activities.

**Describe the solution you'd like**
Use the `ILogger.LogSecurityEvent` extension.

**Additional context**
Maybe we should wait until [this issue](https://github.com/arcus-azure/arcus.observability/issues/131) is done bc otherwise we'll get the SQL package dependency in our security package which is by all means not something we want.

**Comment by tomkerkhove** [comment]
Can you elaborate a bit more what you want to achieve? You want to provide a security event for every single get secret operation per provider, is that correct?

**Comment by stijnmoreels** [comment]
> Can you elaborate a bit more what you want to achieve? You want to provide a security event for every single get secret operation per provider, is that correct?

We have created the possibility to log security events with the `.LogSecurityEvent` in the `Arcus.Observability.Telemetry.Core` but that package has still a package reference to a SQL package. This issue is created to make sure when this SQL package is removed, we add the `Arcus.Observability.Telemetry.Core` package to the `Arcus.Security.Core` package and write a security event for every secret that is being requested.
