### ISSUE TITLE
Provide capability to opt-in for dependency tracking for Azure Key Vault

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.security#182]
**Is your feature request related to a problem? Please describe.**
Provide capability to opt-in for dependency tracking for Azure Key Vault

**Describe the solution you'd like**
```csharp
// Adding the Azure Key Vault secret provider with the built-in overloads
builder.AddAzureKeyVaultWithManagedServiceIdentity(keyVaultUri, useDependencyTracking: true);
```

**Additional context**
We need to see if we can do this by bringing in that dependency or if that would cause circular references

**Comment by stijnmoreels** [comment]
We could already add the dependency tracking without the `Arcus.Observability` package but using the same dependency message format so it works the same? That way we eliminate [this problem](#177) and we can include this in v1.4.0.

**Comment by stijnmoreels** [comment]
Hmm, also, can't we just the `TelemetryFilter` from the Observability package to filter out these dependency calls instead of passing yet another bool to control the behavior of the secret provider?

**Comment by tomkerkhove** [comment]
Let's update Observability to align with https://github.com/arcus-azure/arcus.observability/issues/131#issuecomment-708168766 so you can already use it here.
