### ISSUE TITLE
Question - is it okay that the cache configuration in the composite secret provider is always `null`?

### ISSUE THREAD

**Issue by stijnmoreels** [arcus-azure/arcus.security#187]
**Description**
The secret store works in such a fashion that all the registered secret providers are combined together into a single `CompositeSecretProvider` that will run through all of them in search for the secret. This composite instance implements the `ICachedSecretProvider` because it supports caching in the secret store, but... that also means that we have to implement the `ICachedSecretProvider.CacheConfiguration` which is an instance of `ICacheConfiguration`.

Righ now this is always `null` (see: [this line](https://github.com/arcus-azure/arcus.security/blob/6b878e89f8bef8b02bcbcbd3f32ebfece039019b/src/Arcus.Security.Core/CompositeSecretProvider.cs#L41)).

I was thinking of creating an `CompositeCacheConfiguration` that includes the configuration by registered cached secret provider, but that is maybe too much and/or not really useful since it will only be used within the secret provider itself... 

Thoughts?

**Comment by tomkerkhove** [comment]
What are you pointing to in the wiki? AFAIK we don't use that because everything is in the repo.

The question is, do we need it here? it doesn't provide any info because it's a composite, no? Maybe `NotSupportedException` is more suitable here I think?

**Comment by stijnmoreels** [comment]
> What are you pointing to in the wiki? AFAIK we don't use that because everything is in the repo.

😅 that was a mistake, sorry 'bout that.

**Comment by stijnmoreels** [comment]
> The question is, do we need it here? it doesn't provide any info because it's a composite, no? Maybe NotSupportedException is more suitable here I think?

I don't think we need it indeed, maybe a not supported will be more suiteble, yes.

**Comment by fgheysels** [comment]
Throw an exception or return a 'NullObject' ?  Don't know what is most suitable in this situation.

**Comment by stijnmoreels** [comment]
> Throw an exception or return a 'NullObject' ? Don't know what is most suitable in this situation.

I would use a `NullObject` in a system where it's being used, so you can 'ignore' or 'skip' the functionality with the `NullObject`. In this cause however, this is not the case as the cache configuration is only used within the context of the caching secret providers (and not in the composite end result).  I'll throw that exception maybe.
