### ISSUE TITLE
Provide support for using Azure.Identity 📦 for Azure Key Vault

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.security#191]
**Is your feature request related to a problem? Please describe.**
Provide support for using Azure.Identity 📦 for Azure Key Vault to support users who are already using that way of authenticating.

**Describe the solution you'd like**
https://docs.microsoft.com/en-us/dotnet/azure/authentication

Thoughts?

**Comment by stijnmoreels** [comment]
Ah, yes, this seems like the recommended approach. How would this effect the current authentication interface? Can we make it work with the existing signature or do we have to break something?

**Comment by tomkerkhove** [comment]
I would check what the impact is and how we can move this in, maybe it's fairly simple to do.

**Comment by stijnmoreels** [comment]
I think it's fairly simple to do. I'll try to come up with something and create a PR when I'm done.

**Comment by tomkerkhove** [comment]
Thanks!

**Comment by tomkerkhove** [comment]
I think, long-term, we would only have to support Azure.Identity since they made it a lot easier but let's see how that goes.

**Comment by stijnmoreels** [comment]
Looked at some possibilities, and created a [draft PR](https://github.com/arcus-azure/arcus.security/pull/193).

**Comment by tomkerkhove** [comment]
@fgheysels @gverstraete @wseye @SamVanhoutte Who of you are already using Azure.Identity package? Would it be a problem if we deprecate the current approach (and support it until 2.0) where we prefer Azure.Identity instead of the old approach?

**Comment by tomkerkhove** [comment]
Re-opening since docs are not clear enough based on https://github.com/arcus-azure/arcus.security/issues/217

**Comment by stijnmoreels** [comment]
Maybe someone else should take this up as it's for us hard to see where it's unclear.
