### ISSUE TITLE
KeyVault secret provider not working of Azure Functions.

### ISSUE THREAD

**Issue by Fabiest** [arcus-azure/arcus.security#194]
**Describe the bug**
In an Azure Function, either locally or in an Azure environment, the secret provider fails to find the intended secret throwing the following exception: "Arcus.Security.Core.SecretNotFoundException: 'The secret CanonicEventHubSendConnectionString was not found.'".

![image](https://user-images.githubusercontent.com/43171436/94942275-fa5ae600-04cd-11eb-9d2b-55787c867377.png)

![image](https://user-images.githubusercontent.com/43171436/94942470-40b04500-04ce-11eb-8d6b-4142a55b7234.png)

**To Reproduce**
Create an Azure function project, register the secret provider in function startup and try to retrieve a secret later.

Function Startup:
```using Emsa.Ingestion.Vms.Transform.Configurations;
using Microsoft.Azure.Functions.Extensions.DependencyInjection;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;

[assembly: FunctionsStartup(typeof(Emsa.Ingestion.Vms.Transform.Startup))]
namespace SomeNamespace
{
    public class Startup : FunctionsStartup
    {
        public override void Configure(IFunctionsHostBuilder builder)
        {
            var serviceProvider = builder.Services.BuildServiceProvider();
            var config = serviceProvider.GetRequiredService<IConfiguration>();

            // Configuration for the ISecretProvider using Arcus.Security module
            // In this case we are adding KeyVault as a SecretProvider
            builder.ConfigureSecretStore(stores =>
            {
                var keyVaultUri = config[Constants.KeyVaultUri];

                // Arcus extension Method
                // The authorization in the keyvault is made with the configured identity, in this case, of the App Function
                // It is required to give the necessary permitions on the keyvault for the manage identity
                stores.AddAzureKeyVaultWithManagedServiceIdentity(keyVaultUri);
            });

            var vmsSingletonServices = new VmsSingletonServices();
            vmsSingletonServices.AddAisTransformSingletons(builder);
        }
    }
}
```

To fetch the secret:

Constructor of the class:
```
private ISecretProvider _secretProvider;

public ConfigurationProvider(ISecretProvider secretProvider)
{
            _secretProvider = secretProvider;
}

public async Task<string> GetEventHubCanonicSendConnectionAsync()
{
    if (string.IsNullOrWhiteSpace(_canonicEventHubSendConnectionString))
    {
            _canonicEventHubSendConnectionString = await _secretProvider.GetRawSecretAsync("CanonicEventHubSendConnectionString");
    }

    return _canonicEventHubSendConnectionString;
}

```

Some function configuration:

{
  "name": "FUNCTIONS_EXTENSION_VERSION",
  "value": "~3"
}

**Expected behavior**
The return of the secret value.

**Additional context**

The following code works:
```
var azureServiceTokenProvider = new Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProvider();
var keyVaultClient = new Microsoft.Azure.KeyVault.KeyVaultClient(new Microsoft.Azure.KeyVault.KeyVaultClient.AuthenticationCallback(azureServiceTokenProvider.KeyVaultTokenCallback));
var keyVaultUri = GetEnvironmentVariable("KeyVaultUri");

var secretValue = await keyVaultClient.GetSecretAsync(keyVaultUri, "CanonicEventHubSendConnectionString");
```
**Additional Notes**
I asked a colleague that had a previous example put together, which is basically the same code I have (in terms or Arcus setup) and he is 100% sure it was working but now it is not (even without doing any code changes or package updates).

**Comment by tomkerkhove** [comment]
This will be another one of those fun Azure Function edge-cases. @stijnmoreels can you try if you can reproduce this please? Also we should check if we can provide a similar overload where we provide the IConfiguration so that people don't have to get it themselves maybe?

**Comment by tomkerkhove** [comment]
@Fabiest Is the `ConfigurationProvider` added to the services through `AddAisTransformSingletons`? What does your function look like? What if you inject ISecretProvider in there directly and consume it there?

**Comment by stijnmoreels** [comment]
Building the `IServiceProvider` yourself and adding services afterwards is against the policy of the .NET Core dependency injection and is I think not even possible or will be blocked/result in exception. Normally, outside Azure Functions, you get the `IConfiguration` within the lamdba of the secret store builder registration, but within Azure Functions, this doesn't seem to be available. 

What you can do, is using v1.1.0 of the Microsoft.Azure.Functions.Extensions, which allows you to do the following.
```csharp
public void ConfigureServices(IFunctionHostBuilder builder)
{
    IConfiguration configuration = builder.GetContext().Configuration;
}
```

**Comment by tomkerkhove** [comment]
That's one option but I'm curious if that's the cause, I don't think so..

**Comment by stijnmoreels** [comment]
Yeah, it's possible (or even highly possible) that's it's related to this #170 .

**Comment by tomkerkhove** [comment]
I doubt that because it works if they use Key Vault SDK directly with managed identity. (see above)

**Comment by tomkerkhove** [comment]
In other words, let's try to reproduce this!

**Comment by stijnmoreels** [comment]
@Fabiest , which version of the Arcus.Security packages did you use for this?

**Comment by Fabiest** [comment]
@stijnmoreels, the version for the Arcus.Security was 1.3.0

**Comment by stijnmoreels** [comment]
Tested with a fresh Azure Functions app, using the configuration to retrieve the Azure Key Vault URI, and the managed identity authentication to retrieve the secret.
Injected an `ISecretProvider` instance and retrieved the secret succeeded, _when_ using the **1.3.1** version of the **Microsoft.Azure.Functions.Extensions**.

**Comment by fgheysels** [comment]
Does there exist an access policy on your KeyVault for the identity of the Azure Function ?

**Comment by fgheysels** [comment]
Is the `SecretNotFoundException` that is being thrown preceded by another exception ?

I have something similar with a `KeyVaultSecretProvider` that I'm using in an ACI.   Don't know however if the problem exists in Arcus.  The issue that I'm experiencing is like this:

- Every time I redeploy the ACI, my container fails to start.
- An exception is thrown when the `KeyVaultSecretProvider` tries to retrieve a secret from KeyVault; the exception that is being thrown is this:

```
Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProviderException: Parameters: Connection String: [No connection string specified], Resource: https://vault.azure.net, Authority: https://login.windows.net/bccfoobar Exception Message: Tried the following 3 methods to get an access token, but none of them worked.
Parameters: Connection String: [No connection string specified], Resource: https://vault.azure.net, Authority: https://login.windows.net/bccfoobar. Exception Message: Tried to get token using Managed Service Identity. Access token could not be acquired. The operation was canceled.
Parameters: Connection String: [No connection string specified], Resource: https://vault.azure.net, Authority: https://login.windows.net/bccfoobar. Exception Message: Tried to get token using Visual Studio. Access token could not be acquired. Environment variable LOCALAPPDATA not set.
Parameters: Connection String: [No connection string specified], Resource: https://vault.azure.net, Authority: https://login.windows.net/bccfoobar. Exception Message: Tried to get token using Azure CLI. Access token could not be acquired. No such file or directory
```
- Deleting the ACI resource and redeploying, and then no problems

**Comment by Fabiest** [comment]
@stijnmoreels, I don't have Microsoft.Azure.Functions.Extensions 1.3.1 available via nuget because I'm using .NET standard 2.1 and this is how we intended. (sorry for forgetting to mention that)
![image](https://user-images.githubusercontent.com/43171436/95569589-b01dbb80-0a1d-11eb-8c3d-224d2e15d957.png)

**Comment by stijnmoreels** [comment]
Hmm, this is what I got now, even with `netstandard`. The extensions package makes it available to use `.GetContext()`. Either way, building the `IServiceProvider` yourself is wrong .NET Core setup and we can't garantuee the consequences of that.

```xml
<ItemGroup>
   <PackageReference Include="Arcus.Security.AzureFunctions" Version="1.3.0" />
    <PackageReference Include="Arcus.Security.Providers.AzureKeyVault" Version="1.3.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.1.0" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.3" />
</ItemGroup>
```

**Comment by Fabiest** [comment]
Hello @stijnmoreels, If I understood ok, what you think we should not do is:
`
var serviceProvider = builder.Services.BuildServiceProvider();
`

So, just to test, I tried the code below and I still get the same error:
```
public override void Configure(IFunctionsHostBuilder builder)
{
    // Configuration for the ISecretProvider using Arcus.Security module
    // In this case we are adding KeyVault as a SecretProvider
    builder.ConfigureSecretStore(stores =>
    {
        var keyVaultUri = "https://hpims-dev-we-vault.vault.azure.net/";

        // Arcus extension Method
        // The authorization in the keyvault is made with the configured identity, in this case, of the App Function
        // It is required to give the necessary permitions on the keyvault for the manage identity
        stores.AddAzureKeyVaultWithManagedServiceIdentity(keyVaultUri);
    });

    var vmsSingletonServices = new VmsSingletonServices();
    vmsSingletonServices.AddAisTransformSingletons(builder);
}
```

Am I doing something wrong or misunderstanding something?

**Comment by stijnmoreels** [comment]
Yeah, that's it. It didn't seem like it was the cause of the error, but it's definitly something that needed attention in our regard. Still bit strange that you get this. Did you check @fgheysels [proposal](https://github.com/arcus-azure/arcus.security/issues/194#issuecomment-704967898) or [this](https://github.com/arcus-azure/arcus.security/issues/194#issuecomment-705375968) here above?

**Comment by Fabiest** [comment]
Don't think @fgheysels proposal fits the situation because I don't have any other exception before related to key vault. Also, sorry if I'm wrong, but it seems he his talking about containers?? Which is not my case.
By the way, what is ACI?

**Comment by stijnmoreels** [comment]
> By the way, what is ACI?

Azure Container Instance, propably. 😉

**Comment by stijnmoreels** [comment]
You could also try with a preview package of this library where we use more specific exceptions. v.4.0-alpha.
Still strange we can't reproduce it which makes me wonder if it's indeed like @fgheysels said something with access policies, connection string structure, ... a different type of authentication can maybe help/troubleshoot this.

**Comment by tomkerkhove** [comment]
We'll have a closer look at this @Fabiest but can you check #196 please? This might be the same issue you are suffering from.

**Comment by tomkerkhove** [comment]
Any update if #196 helped you @Fabiest ?

**Comment by tomkerkhove** [comment]
@Fabiest can you try with https://github.com/arcus-azure/arcus.security/releases/tag/v1.4.0-beta please?

**Comment by Fabiest** [comment]
@tomkerkhove, pologies for the delay.
Today I was recreating the issue and... no issue. I also checked with my colleague that tested and had the same and it worked for him as well without changing anything.
A mistery this one. I will keep testing over some days to see what happens, but I guess this can be closed??
