### ISSUE TITLE
Migrate from `Polly-Signed` 📦 to `Polly` 📦

### ISSUE THREAD

**Issue by fgheysels** [arcus-azure/arcus.security#195]
I'm using the Arcus.KeyVaultSecretProvider in a program that is running as a container in an Azure Container Instance.   This program uses Polly for retrying operations that have failed.

When my program starts, the container almost immediately stops.   The logs of the container contain this error message:

![image](https://user-images.githubusercontent.com/3605786/95426316-fa336e00-0945-11eb-86bc-b2315e7c81b0.png)

As it turns out, my program is using Polly 7.2.1 whereas the Arcus KeyVaultSecretProvider is using a package called `Polly-Signed` 5.9.0 which is build for .NET Standard 1.1 / .NET Framework 4.5 and dates back to April 2018.

I've now resolved the issue by also using this Polly-Signed package, so my container is now starting but I'm wondering if KeyVaultSecretProvider should also target the regular 'Polly' package ?  I'm also wondering how we can avoid such dependency conflicts in Arcus.

**Comment by tomkerkhove** [comment]
Apparently yes, I was not awre of this and we should migrate to `Polly` indeed. Sorry about that!
