### ISSUE TITLE
Using User assigned identity for KeyVault authentication requires newer version (>=1.4) of Microsoft.Azure.Services.AppAuthentication package

### ISSUE THREAD

**Issue by petergerritsen** [arcus-azure/arcus.security#196]
**Describe the bug**
When using a User Assigned Identity in an App Service for authenticating with KeyVault and retrieving a secret we get a KeyNotFoundException. Installing version 1.6.0 of Microsoft.Azure.Services.AppAuthentication resolved the issue.

**To Reproduce**

- Create an App Service
- Assign a user assigned identity which has secret get and list permissions on the KeyVault
- Setup Arcus with the KeyVault provider with connectionstring `RunAs=App;AppId={clientId of user assigned identity}`
- Use the ISecretprovider to retrieve a secret from the KeyVault
- The exception is thrown with message `(The secret <SecretName>was not found.) The secret <SecretName> was not found. None of the configured secret providers contains the requested secret`

**Expected behavior**
The app can access the secret

**Additional context**
Versions used
 - Arcus.Security.Providers.AzureKeyVault 1.3.0
 - Arcus.Security.Secrets.Core 0.4.0

After using a preview version with logging enabled I got the following error: `Unhandled exception. System.ArgumentException: Connection string RunAs=App;AppId={client id ellided} is not valid. Must contain 'TenantId' attribute and it must not be empty.`

I've found the following thread on StackOverflow describing the same issue: https://stackoverflow.com/questions/63608985/azure-app-service-with-user-assigned-managed-identity-crashes-application
The accepted answer suggests installing a newer version (>= 1.4) of the Microsoft.Azure.Services.AppAuthentication package. Installing 1.6.0 did indeed resolve the issue.

**Comment by petergerritsen** [comment]
This might be unnecessary if https://github.com/arcus-azure/arcus.security/pull/193 is merged. But for current troubleshooting purposes it could prove useful to have this issue logged anyway.

**Comment by tomkerkhove** [comment]
Huh nice find, thanks for letting us know! Did you try aligning the versions of your Arcus Security packages to the following (just for sake of testing):
- Arcus.Security.Providers.AzureKeyVault 1.3.0
- Arcus.Security.Secrets.Core 1.3.0

**Comment by tomkerkhove** [comment]
But we are indeed migrating to the new official Microsoft.Identity package which would give better support.
