### ISSUE TITLE
Migrate from `Microsoft.Azure.KeyVault` to `Azure.Security.KeyVault.Secrets` 📦

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.security#197]
**Is your feature request related to a problem? Please describe.**
Migrate from `Microsoft.Azure.KeyVault` to `Azure.Security.KeyVault.Secrets` 📦 since it's deprecated

**Additional context**
See https://www.nuget.org/packages/Microsoft.Azure.KeyVault

**Comment by stijnmoreels** [comment]
This PR #193 is already doing this, no?

**Comment by tomkerkhove** [comment]
Yes but it's not deleting the old package which we should get rid of

**Comment by stijnmoreels** [comment]
> Yes but it's not deleting the old package which we should get rid of

So, also deleting the types that uses this? (I'm thinking about our `IKeyVaultAuthentication` implementations); these are breaking changes, right? Is v1.4.0 then OK here?

**Comment by tomkerkhove** [comment]
Yes, we should only mark them as obsolete for now and remove them in a new major change.

If you think we can keep them supported side-by-side we could also do that but think we should standardize on that library under the hood as well to reduce the code?

**Comment by stijnmoreels** [comment]
Yes, agree so we'll support them both now but remove the obsolete ones in the next major version.
