### ISSUE TITLE
Should SecretName mutation be baked in into the SecretProvider implementation

### ISSUE THREAD

**Issue by fgheysels** [arcus-azure/arcus.security#199]
Right now, when adding a `ISecretProvider` implementation to the SecretStoreBuilder, a Func can be specified for mutating the secretname before the secret is retrieved.

I'm wondering if the `ISecretProvider` implementations should have a default secretname mutation baked in ?  If we look at the ConfigurationProviders in .NET for instance, we pass in a 'hierarchical' config value, the colon (`:`) is used as separator.  However, for environment variables, the separator is `__` and in KeyVault, the separator is `--`.

Therefore, I'm wondering if each `ISecretProvider` implementation should have a default 'mutation scheme' implemented.  This would allow users of secretproviders to be oblivious on how the secretname should be mutated.
It will allow users to specify that the secret `ConnectionStrings:MyDatabase` must be retrieved, and each SecretProvider implementation that is used, makes sure that the secretname is changed to the correct pattern.  The KeyVault provider makes sure that a secret named `ConnectionStrings--MyDatabase` is looked up; the DockerSecretsProvider searches for a secret named `ConnectionStrings__MyDatabase`.

See also the discussion in this [PR](https://github.com/arcus-azure/arcus.security/pull/171#discussion_r502914253).

**Comment by tomkerkhove** [comment]
That would help, but the func is not only for that. For example, you might use 3 providers and always use `:` as a seperator where Azure Key Vault provider would automatically replace it with `-`; but we actually don't want to do that and replace `:` with an empty string. In the proposal above, we would not have control over that anymore as a user if I understand it correctly?

Another question is, should we mutate by default? Wouldn't that be very odd as a user? If I request to have secret "Foo-Bar" and we don't configure any mutation, wouldn't you as a user expect that it just takes that? Or would you only do it for those where, ie `:`, is a prohibited character? I'm just thinking about people who might be confused because they are not aware of it.

What's your main concern?

**Comment by fgheysels** [comment]
Not really a concern, just a thought.
Instead of specifying `null` as the default `mutateSecretName` implementation, a default could be provided which translates `:` to the hierarchy separation character used by that implementation.
I was just wondering if we should do that, because the way SecretProviders work, are very similar to how retrieving values from the Configuration works.  It might be confusing for users that they cannot just specify `GetSecretAsync("ConnectionStrings:Foo")` to retrieve a connectionstring from KeyVault if they haven't specified the mutation function.  

I see that right now that it is only possible to pass in the `mutateSecretName` func when calling the `AddProvider` extension method.  Shouldn't it be possible to specify it via the ctor of the ISecretProvider implementation as well ?  (Suppose you want to use the secret provider directly ? )

**Comment by stijnmoreels** [comment]
> I see that right now that it is only possible to pass in the mutateSecretName func when calling the AddProvider extension method. Shouldn't it be possible to specify it via the ctor of the ISecretProvider implementation as well ? (Suppose you want to use the secret provider directly ? )

If you want to pass along with your own `ISecretProvider`, you should wrap it in a `MutatedSecretProvider` (just like you would have to wrap it in a `CachedSecretProvider` if you want caching). But indeed, this is not necessary bc we do that for you internally. You onlyl have to pass a long the mutation to the `.AddProvider`.

**Comment by fgheysels** [comment]
Isn't that a very big workaround for something that should be rather simple ?
What if I do not use the AddProvider extension methods, and want to instantiate a secret provider myself ?

**Comment by stijnmoreels** [comment]
Hmm, I don't think so, it seems to be the perfect solution for th secret store; to work with a proxy. Can you maybe give us an use case where you wouldn't use the secret store and still want to use the secret provider? I think I'm not fully on board with what you need or what you miss.

**Comment by tomkerkhove** [comment]
> Hmm, I don't think so, it seems to be the perfect solution for th secret store; to work with a proxy. Can you maybe give us an use case where you wouldn't use the secret store and still want to use the secret provider? I think I'm not fully on board with what you need or what you miss.

Use a secret provider to interact with a given secret store. Secret Store is good for querying but not for managing such as setting secrets because you want to choose where to end up with the secret.

Think having a wrapper for just mutation is overkill as well imo.

**Comment by stijnmoreels** [comment]
We could include the necessary secret name mutation in the registration of the secret provider (not the provider itself); that way we would not have a dedicated secret provider for secret name mutation.
Placing the mutation the secret providers itself, will introduce not only a lot of duplication (and possible forgetting of adding it), it will also have to include the exception handling and logging/tracking of the secret names that is now currently available in this dedicated secret provider.
Also, one have to make sure that it includes for both caching and non-caching as this provides extra overloads.
So, with all this, it was logical to place it somewhere central so all the existing secret providers and future providers would be direclty supported with secret name mutation without thinking about it every time a new one is introduced.

But again, if we move it to the registration and not the provider, we could maybe remove these dedicated providers, but it will not be any difference for the end user, and I think it will make the registration process in the secret store only more complex for new devs.

**Comment by stijnmoreels** [comment]
Closed in favor of https://github.com/arcus-azure/arcus.security/discussions/242
