### ISSUE TITLE
Provide ISecretProvider

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.security#20]
**Is your feature request related to a problem? Please describe.**
We need an interface which consumers can use to pass around that allows them to get the value for a secret.

We will then provide a variety of providers with the concrete implementation per secret store.

**Describe the solution you'd like**
Provide an `ISecretProvider` that will be used to plug in the secret store that you want to use.

It should only expose 1 operation for now: `GetAsync(string name)`

This should end up in the `Arcus.Security.Core` 📦 .

**Comment by SamVanhoutte** [comment]
Completed through [PR 32](https://github.com/arcus-azure/arcus.security/pull/32)
