### ISSUE TITLE
Provide capability to assign name to providers added to the secret store 

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.security#204]
**Is your feature request related to a problem? Please describe.**
Provide capability to assign name to providers added to the secret store.

**Describe the solution you'd like**
This way, we can inject the secret store in dependencies and request the secret provider with a given name to interact with only that secret store.

**Comment by stijnmoreels** [comment]
Are we allowing multiple providers to be registered with the same name?

Also, we should consider changing the `.AddProvider` so we can pass options too.

**Comment by tomkerkhove** [comment]
I would say no, they should be unique.

In terms of the options, fine for me as I don't see any problem (as long as we are backwards compatible for now.
