### ISSUE TITLE
Provide capability to opt-in for security events

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.security#205]
**Is your feature request related to a problem? Please describe.**
Provide capability to opt-in for security events instead of turning them on by default as they generate a lot of telemetry which burries more relevant information.

**Comment by stijnmoreels** [comment]
Problem here, is that we can create a filter for this, but then it's still by default on. We don't have any 'hook' for the Serilog configuration. We could, however, make the security events for our own Azure Application Insights log sink by default off.

**Comment by tomkerkhove** [comment]
Or we provide configuration for the pump and only then it writes the log entry?
