### ISSUE TITLE
KeyVault SecretProvider: Allow creation/storing of new secrets

### ISSUE THREAD

**Issue by mbraekman** [arcus-azure/arcus.security#206]
**Is your feature request related to a problem? Please describe.**
Would it make sense to have the SecretProvider for KeyVault, also allow users to create secrets?
In a specific situation, we need to generate tokens at runtime, which need to be stored in KeyVault for future reference. Seeing as this SecretProvider is already being used to retrieve existing secrets, we would prefer to use the same library/package to store these new secrets.

**Describe the solution you'd like**
Next to the GetRawSecretAsync and GetSecretAsync-methods, provide a method such as SetSecretAsync:
`public async Task<Secret> SetSecretAsync(string secretName, string secretValue, bool enabled, , string contentType = "", DateTime? expirationDate = null)`
Where the returned object, contains the version-number of the newly created secret.

**Describe alternatives you've considered**
Directly consuming the SDK, having to do the authentication against KeyVault ourselves.

**Comment by tomkerkhove** [comment]
Definately a valid request and I have the same need; it's coming soon!

**Comment by mbraekman** [comment]
Let me know if/where we can help out with this.

**Comment by tomkerkhove** [comment]
Open work:
- [ ] Provide capability to store in Azure Key Vault
- [ ] Provide integration with cached provider so that it gets refreshed
- [ ] Provide overview in docs what provider supports what

**Comment by fgheysels** [comment]
Wondering if setting / managing secrets should be in the SecretProvider.  From the name, I'd think that the provider can only retrieve secrets.  Shouldn't this functionality be put in a separate class ?

**Comment by tomkerkhove** [comment]
The core will be in the secret provider but won't be surfaced through `ISecretProvider` but rather something like `ISecretManagement`/`ISecretManager`.

This is what you are looking for as well, right?

**Comment by fgheysels** [comment]
I think i can live with that :)

**Comment by tomkerkhove** [comment]
But I'm open to more suggestions of course!
