### ISSUE TITLE
Improve extension methods for IFunctionsHostBuilder

### ISSUE THREAD

**Issue by fgheysels** [arcus-azure/arcus.security#212]
I'm currently checking out the extension methods that are provided in Arcus.Security.AzureFunctions (1.4.0 beta 2).  
I think the functionality provided there is really nice but I wonder:

- why is the method called `ConfigureSecretStore` whereas you're merely adding a secretstore provider ?
- shouldn't this be aligned with how it's done in ASP.NET projects ?  
- When I try to add KeyVault as a secret store, it seems that it is not possible to define a secret-name mutation function.

**Comment by tomkerkhove** [comment]
I'm not following I think because `ConfigureSecretStore` for Azure Functions is just the same as with .NET Core support that allows you to add multiple providers.

With that support, you are actually using the same extensions and have the same features?

**Comment by fgheysels** [comment]
Yeah, sorry, my bad.  Seems like I was to fast drawing conclusions.

What concerns the missing `mutateSecretName` parameter:  I was using the latest stabel version (v1.3.0) of `Arcus.Security.Providers.AzureKeyVault`.   Seems like only the beta versions have this parameter.

Issue can be closed.
