### ISSUE TITLE
Arcus.Security 1.4.0 beta 2 seems to have a dependency on Asp.Net framework

### ISSUE THREAD

**Issue by fgheysels** [arcus-azure/arcus.security#213]
This is related to #189 

I'm using `Arcus.Security` and `Arcus.Security.Providers.AzureKeyVault` (v 1.4.0-alpha) in a simple containerized console application where my base image is  `mcr.microsoft.com/dotnet/core/runtime:3.1-alpine`.
All is working well.

I've upgraded  `Arcus.Security` and `Arcus.Security.Providers.AzureKeyVault` in my project to 1.4.0-beta-2 and now my container fails to start with the following error:

> It was not possible to find any compatible framework version
The framework 'Microsoft.AspNetCore.App', version '3.1.0' was not found.
>  - No frameworks were found.

**Comment by tomkerkhove** [comment]
Due to https://github.com/arcus-azure/arcus.observability/issues/162

**Comment by stijnmoreels** [comment]
This should be resolved due to #226
