### ISSUE TITLE
How can I use the ISecretProvider if I do not want to use a HostBuilder

### ISSUE THREAD

**Issue by fgheysels** [arcus-azure/arcus.security#214]
I've a project where I want to be able to configure and use one or multiple ISecretProviders, but I do not have (and I don't need) a HostBuilder instance.

In this scenario, how can I easily make use of the Arcus SecretProviders ?   I thought to do it like this:

```csharp
var secretProviderBuilder = new SecretStoreBuilder(services);

var secretSettings = config.GetSecretProviderSettings();

if (secretSettings.Type.Equals("KeyVault", StringComparison.OrdinalIgnoreCase))
{
    secretProviderBuilder.AddAzureKeyVaultWithManagedServiceIdentity(secretSettings.KeyVault.KeyVaultUrl);
}
else
{
   secretProviderBuilder.AddConfiguration(config.Configuration);
}

 var secretProvider =  services.BuildServiceProvider().GetService<ISecretProvider>();
```

But that doesn't work.  The SecretProviders are not registered in the ServiceCollection.   I've inspected the code and it turns out that I should call the `RegisterSecretStore` method on the `SecretStoreBuilder`, but that method is internal.

**Comment by tomkerkhove** [comment]
You can still register providers seperately without the configuration store but it looks like our docs are no longer showing this so we should include that again @stijnmoreels.

**Comment by tomkerkhove** [comment]
Hm I thought we still supported that but it doesn't look like it anymore @stijnmoreels, is that correct? If so, we should re-add it and support using service provider with `SecretStoreBuilder`

**Comment by tomkerkhove** [comment]
We'll add support for this on IServiceCollection - https://github.com/arcus-azure/arcus.security/issues/215
