### ISSUE TITLE
Introduce `AddSecretStore` for configuring the store on `IServiceCollection`

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.security#215]
**Is your feature request related to a problem? Please describe.**
Introduce `AddSecretStore` for configuring the store on services so that people don't have to rely on `HostBuilder`.

**Describe the solution you'd like**
The same experience as we have with `HostBuilder`, but with `IServiceCollection`

**Comment by tomkerkhove** [comment]
It would look similar to this:
```csharp
services.AddSecretStore(secretStoreBuilder =>
{
    secretStoreBuilder.AddAzureKeyVaultWithManagedServiceIdentity(secretSettings.KeyVault.KeyVaultUrl);
});
```

Ok for you @fgheysels? You'll have to use the IConfiguration that is injected in the startup to get access to it since we don't have that info for now.

**Comment by fgheysels** [comment]
That would be ok I guess.

Now I'm just wondering:  if you have an extension method on `ServiceCollection`, what's the added value of the `ConfigureSecretStore` extension method on `IHostBuilder` ?

**Comment by tomkerkhove** [comment]
It makes it easier with IHostBuilder because there we give IConfiguration and you don't have to get it yourself. 

In cases where you have a Startup that's fine, but if you do the full bootstrapping in Program (ie workers) that's not the case, or you have to build the configuration separately and pass that to the HostBuilder flow which is less ideal.

For example:
```csharp
return Host.CreateDefaultBuilder(args)
                       .ConfigureAppConfiguration(configurationBuilder =>
                       {
                           configurationBuilder.AddEnvironmentVariables();
                       })
                       .ConfigureSecretStore((configuration, secretStoreBuilder) =>
                       {
                           var vaultUrl = configuration["KEYVAULT_URL"];

                           secretStoreBuilder.AddEnvironmentVariables(prefix:"HYPERION_");
                           
                           // Read from Azure Key Vault when not found in environment variables
                           secretStoreBuilder.AddAzureKeyVaultWithManagedIdentity(vaultUrl, allowCaching: true);
                       });
```

Is this a must? Definitely not, but it puts the secret store more front and center and aligns with how configuration is done in .NET. Is it bad to only use IServiceCollection? No.

We're giving the options to users, up to them to decide what their preference is.

**Comment by stijnmoreels** [comment]
Couldn't explain it better 😄 .

**Comment by fgheysels** [comment]
That definitely makes sense.   Just like playing the devils advocate.
