### ISSUE TITLE
Registering multiple AzureKeyVaultProviders

### ISSUE THREAD

**Issue by fgheysels** [arcus-azure/arcus.security#232]
**Description**

I have a project that requires access to 2 different keyvault resources.  Ideally, I'd use 2 separate Arcus KeyVaultProviders for this, but I wonder if this is possible.
Next to that, I wonder if it would be possible to be able to get the SecretProvider instance that accesses a specific keyvault ?  For instance, in some classes I know that I need to retrieve secrets from KeyVault A.  In another class, I know that I need the provider that is connected to KeyVault B.
Is it possible to do that ?  I see that I can register a KeyvaultProvider and specify a 'name'.  Can I use that name to get hold of a specific secretprovider ?

**Comment by fgheysels** [comment]
I see that the `CompositeSecretProvider` class has a member `GetProvider`, so I assume that this allows me to retrieve a specifc secretprovider.

It would be nice if this could be documented though :)

**Comment by tomkerkhove** [comment]
This feels like a good use-case for our secret store unless you don't want people to always go and poke both providers. Otherwise you'll have to use the `CompositeSecretProvider` but would try to avoid that over secret store.

> Is it possible to do that ? I see that I can register a KeyvaultProvider and specify a 'name'. Can I use that name to get hold of a specific secretprovider ?

Yes, you definitely can do that! You can find more about that in [our docs](https://security.arcus-azure.net/features/secret-store/named-secret-providers).

**Comment by stijnmoreels** [comment]
> I have a project that requires access to 2 different keyvault resources. Ideally, I'd use 2 separate Arcus KeyVaultProviders for this, but I wonder if this is possible.

Yes, that's possible. The secret store doesn't require 'unique' secret provider types. It only runs through all the different registered secret providers. You can have several Azure Key Vault secret providers, pointing to different vaults.

> Next to that, I wonder if it would be possible to be able to get the SecretProvider instance that accesses a specific keyvault ? For instance, in some classes I know that I need to retrieve secrets from KeyVault A. In another class, I know that I need the provider that is connected to KeyVault B.

Yes, like Tom said, this is documented under _Named secret providers_ which does this exactly: getting specific secret provider registrations. In order to retrieve these instances, you'll have to inject `ISecretStore` into your dependent services which gives you access to all the `.GetProvider` overloads. Make sure that you register the secret providers with an unique name in the secret store, otherwise it will fail with `NotSupportedException`s.

**Comment by stijnmoreels** [comment]
> Otherwise you'll have to use the CompositeSecretProvider but would try to avoid that over secret store.

I don't think that's required in this use case. I think everything described here can be done with the secret store.

**Comment by tomkerkhove** [comment]
> I don't think that's required in this use case. I think everything described here can be done with the secret store.

That remark was in case you don't want/can use our secret store.

**Comment by stijnmoreels** [comment]
Also, I'm writing a new [blog post](https://github.com/arcus-azure/arcus/issues/109) for the Arcus.Security v1.4 release which will include some extra examples on named secret providers and use cases.

**Comment by tomkerkhove** [comment]
Make sure to backport them in our docs if need be.

**Comment by fgheysels** [comment]
Thanks for the link to the documentation on the named provider.   I couldn't find it myself yesterday.
I started [here](https://security.arcus-azure.net/) but how do you navigate to that specific page ?

**Comment by stijnmoreels** [comment]
> Thanks for the link to the documentation on the named provider. I couldn't find it myself yesterday.
> I started [here](https://security.arcus-azure.net/) but how do you navigate to that specific page ?

Features (title) > Secret store (title) > What is it? (link) > Additional features (title) > Retrieving a specific secret provider (link)

**Comment by tomkerkhove** [comment]
As discussed offline I'll prio our docs improvement

**Comment by fgheysels** [comment]
Maybe I should open a new issue for this, but I was thinking:  what if I have 2 sets of 'chained' secretproviders ?
For instance, I have secretprovider A & B , both linked to a different keyvault.
When I want to test locally though, I'd like to retrieve my secrets from the environment variables.  It would be nice if I could do 

```
secretStore.GetProvider("vesselSecrets");
``` 

And this returns me a `CompositeSecretProvider` that contains all secretproviders that were registered by the name "vesselSecrets".   Offcourse, this requires that we can register multiple secretproviders with the same name.

**Comment by tomkerkhove** [comment]
So you're looking for "secret store groups", for a lack of better name.

**Comment by stijnmoreels** [comment]
You can also use the order in which the secret providers are registered. I'd you first register the environment variables inside a DEBUG directive and afterwards the key vaults. You'll get first the environment variables in local development.

**Comment by tomkerkhove** [comment]
That's not going to work in this scenario because it depends on the application "component" and not at build time

**Comment by fgheysels** [comment]
Yes indeed, I'm looking at some kind of 'secretstoregroups'.   
Defining it at compile time using build directives is indeed not a solution here, since I want to be able to define the secretprovider at runtime via the configuration.  Actually, I've solved is like this now:

````pseudo
if( someSetting )
{
     configure.AddKeyVault( ... );
}
else
{
     configure.AddEnvironmentVariables( .... );
}
```

which also does the trick in my case, since I actually don't need them both.  However, should you have a situation where you want to register multiple secretstores and want to use them as well, then it might be handy to be able to register groups of secretstores.

**Comment by tomkerkhove** [comment]
Let's open a dedicated issue to track that

**Comment by fgheysels** [comment]
Done in #237
