### ISSUE TITLE
Registering multiple SecretProviders that are grouped together

### ISSUE THREAD

**Issue by fgheysels** [arcus-azure/arcus.security#237]
It is currently possible to register multiple SecretProviders.    When retrieving a secret, the chain of registered SecretProviders is called, and the secret is retrieved (cfr how the Configuration in .NET works).
It is currently also possible to register a SecretProvider with a specific name so that this specific SecretProvider can be retrieved from the SecretStore.

Wouldn't it be nice if you could combine those 2 features together ?   That is: registering multiple SecretProviders with the same name, so that they would form a 'group' of secretproviders ?   You can then retrieve that group of secretproviders from the SecretStore via the name, just like you can retrieve a single secretprovider by name now.

I don't think the API needs to change for implementing this feature.  I think, behind the scenes a dictionary can be used where the 'key' is the SecretProvider-Name and the value contains a CompositeSecretProvider where all SecretProviders that are registered with the same name are added to.

**Comment by stijnmoreels** [comment]
Yes, indeed, the API could stay the same if we want, but I'll use not an `CompositeSecretProvider` interanally as 'value' for this dictionary, but an `ISecretProvider` since we allow also to cast back to the original, custom `ISecretProvider` instance and that can't be done if also single name registrations are wrapped into a composite.

**Comment by stijnmoreels** [comment]
@fgheysels , you can already look at this PR: #245 were I already started a proposal. I'll hold off for a review bc we should first release v1.4.1 with the `clientId` issue for Azure Key Vault Managed Identity.

**Comment by tomkerkhove** [comment]
Before jumping into code @stijnmoreels it's best to check what is expected.

Looks like currently this is implemented, is that what you would expect @fgheysels?

```
private static IHostBuilder CreateDefaultBuilder(string[] args)
    {
        return Host.CreateDefaultBuilder(args)
                   .ConfigureAppConfiguration(builder => builder.AddCommandLine(args))
                   .ConfigureSecretStore((config, stores) =>
                   {
                        stores.AddEnvironmentVariables(configureOptions: options => options.Name = "Admin Secrets")
                              .AddAzureKeyVaultWithManagedIdentity("https://admin.vault.azure.net", configureOptions: options => options.Name = "Admin Secrets");
                        
                        stores.AddEnvironmentVariables(configureOptions: options => options.Name = "User Secrets")
                              .AddAzureKeyVaultWIthManagedIdentity("https://user.vault.azure.net", configureOptions: options => options.Name = "User Secrets");
                   });
    }
```

**Comment by fgheysels** [comment]
@tomkerkhove :  Yes.   I think you might have situations where you register multiple secretproviders under the same name.

With the above example in mind, if I would do this:

```
var secretProvider = secretStore.GetProvider("Admin Secrets");
```

I'd expect to receive a set of secretProviders (probably a `CompositeSecretProvider`) which allows me to retrieve secrets from both secretproviders.

**Comment by stijnmoreels** [comment]
> With the above example in mind, if I would do this:
> 
> ```
> var secretProvider = secretStore.GetProvider("Admin Secrets");
> ```
> 
> I'd expect to receive a set of secretProviders (probably a `CompositeSecretProvider`) which allows me to retrieve secrets from both secretproviders. Were you expecting something else ?

Yes, that's what happening. When multiple `ISecretProvider`'s are registered with the same name, you'll get a composite of the subset/grouped `ISecretProvider`'s. When only a single `ISecretProvider` is registered with the name, you'll get the actual concrete implementation, so you can cast it to that type (like in the Azure Key Vault situation, where you want to use the actual concrete implementation to store secrets too).
