### ISSUE TITLE
Improve how caching should be specified when registering a secret provider

### ISSUE THREAD

**Issue by fgheysels** [arcus-azure/arcus.security#239]
Right now, there are 2 ways to specify that caching must be used when registering a `ISecretProvider`.
One approach is to specify `allowCaching = true` when registering a SecretProvider.  Another approach is to specify an `ICacheConfiguration`.

These are 2 different approaches to serve the same functionality.   Wouldn't it be nicer to have only one of those options available ?

I would suggest to get rid of the methods which take the `allowCaching` parameter so that you can only specify an `ICacheConfiguration` when you want to enable caching.
If the default caching configuration suffices for a consumer, he should be able to specify caching like this:

```csharp
builder.AddAzureKeyVaultWithManagedIdentity("myvaulturi", CacheConfiguration.Default);
```

(See also my remark on this PR: #236 )

**Comment by tomkerkhove** [comment]
One is for saying "I want cache but don't care about the default", the other is for configuring the cache.

While your suggestion makes sense, people would still know that there is a way to get that default; no?

**Comment by fgheysels** [comment]
> While your suggestion makes sense, people would still know that there is a way to get that default; no?

Documentation can do a lot. :)  This can for instance be mentionned in the XML docs for that parameter.

**Comment by stijnmoreels** [comment]
@tomkerkhove , is this something you can agree on? Or should we hold of for now?

**Comment by tomkerkhove** [comment]
Not really a fan of forcing this property on people but if there is no other way, then docs will have to do.

**Comment by stijnmoreels** [comment]
We can maybe go for both? Adding such a property but leaving the `allowCaching`? I think there's something to say for both approaches.

**Comment by tomkerkhove** [comment]
I think that's what @fgheysels wants to avoid, no?

**Comment by fgheysels** [comment]
Yes indeed.  I think it is better / clearer if there's only one way to enable caching.  But that's just my opinion :)

**Comment by fgheysels** [comment]
I was thinking, maybe we can specify the `CacheConfiguration` as a struct, and then rely on the `default` behaviour of structs, where all members will be initialized to their default value:

```csharp
public struct CacheConfiguration
{
    public TimeSpan Threshold { get; }

    public static readonly CacheConfiguration DefaultCacheConfiguration = new CacheConfiguration(TimeSpan.FromMinutes(5));

     public CacheConfiguration(TimeSpan threshold)
     {
         Threshold = threshold;
     }
    }
````

Then, you could use it like this:

```
 public static void AddSomething(string name, CacheConfiguration cacheConfig = default)
{
            Console.WriteLine(cacheConfig.Threshold);
}
```

If you don't specify the `cacheConfig` , the variable will be initialized with a `CacheConfiguration` instance where the `Threshold` property will have a zero timespan, meaning : no caching.
Offcourse, that might be a bit confusing when you also specify a `DefaultCaching` option where you have a default cache setting and `default(CacheConfiguration)` means no caching.

**Comment by tomkerkhove** [comment]
That might be confusing indeed, let's go with `CacheConfiguration.Default`!
