### ISSUE TITLE
Provide secret provider for command line arguments

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.security#240]
**Is your feature request related to a problem? Please describe.**
Provide secret provider for command line arguments.

**Additional context**
https://github.com/arcus-azure/arcus.security/discussions/238

**Comment by stijnmoreels** [comment]
We may choose to wait until System.CommandLine is officially released.
https://docs.microsoft.com/en-us/archive/msdn-magazine/2019/march/net-parse-the-command-line-with-system-commandline
