### ISSUE TITLE
Reduce standard telemetry for secret store & providers

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.security#269]
**Is your feature request related to a problem? Please describe.**
As of today, Arcus emits the following traces with information verbosity.

For example:
```
[07:44:44 INF] Using ServicePrinciple authentication for Azure Key Vault
[07:44:44 INF] Azure Key Vault secret providers are configured with service principle authentication with app id {ID}.
[07:44:47 INF] Found secret with name '{secret-name}'
```

**Describe the solution you'd like**
All telemetry by Arcus should be emitted as verbose since this is something customers would only need in case of troubleshooting.

Examples are:
https://github.com/arcus-azure/arcus.security/blob/98296116738be281e6771956d6a4586b2e04bf1d/src/Arcus.Security.Core/Providers/MutatedSecretNameSecretProvider.cs#L150

https://github.com/arcus-azure/arcus.security/blob/98296116738be281e6771956d6a4586b2e04bf1d/src/Arcus.Security.Providers.AzureKeyVault/Authentication/ServicePrincipalAuthentication.cs#L62

https://github.com/arcus-azure/arcus.security/blob/98296116738be281e6771956d6a4586b2e04bf1d/src/Arcus.Security.Providers.AzureKeyVault/Authentication/CertificateBasedAuthentication.cs#L62

https://github.com/arcus-azure/arcus.security/blob/98296116738be281e6771956d6a4586b2e04bf1d/src/Arcus.Security.Providers.AzureKeyVault/Authentication/ManagedServiceIdentityAuthentication.cs#L62

https://github.com/arcus-azure/arcus.security/blob/98296116738be281e6771956d6a4586b2e04bf1d/src/Arcus.Security.Tests.Integration/HashiCorp/Hosting/HashiCorpVaultTestServer.cs#L178

https://github.com/arcus-azure/arcus.security/blob/98296116738be281e6771956d6a4586b2e04bf1d/src/Arcus.Security.Core/CompositeSecretProvider.cs#L423

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by fgheysels** [comment]
Remark regarding the traces: It's service principal, not principle :)

**Comment by fgheysels** [comment]
I totally agree with this.  This is also a guideline for library development that I once stumbled upon, but I can't find the source anymore.
Users of Arcus can then turn on verbose logging for Arcus if they want via configuring the loglevel of Arcus to Verbose.

**Comment by tomkerkhove** [comment]
Might be good to review the warnings as well

**Comment by fgheysels** [comment]
> Might be good to review the warnings as well

You mean compile warnings or traces with loglevel warning ?

**Comment by tomkerkhove** [comment]
Traces with warning log level as well
