### ISSUE TITLE
Remove 'old' configuration addition from Azure Key Vault secret provider package

### ISSUE THREAD

**Issue by stijnmoreels** [arcus-azure/arcus.security#285]
**Is your feature request related to a problem? Please describe.**
Our `Arcus.Security.Providers.AzureKeyVault` still contains an extension to add the `ISecretProvider` to an `IConfiguration`.

**Describe the solution you'd like**
We should step away from seeing data as secrets and remove this.

**Additional context**
[Link to code](https://github.com/arcus-azure/arcus.security/blob/955b9bbf0a8f0f4090eaa4fa77dd3f94e04a6222/src/Arcus.Security.Providers.AzureKeyVault/Configuration/SecretProviderConfigurationBuilderExtensions.cs#L18)

**Comment by tomkerkhove** [comment]
If we remove it, then we should deprecate it first and remove in a new major version

**Comment by stijnmoreels** [comment]
> If we remove it, then we should deprecate it first and remove in a new major version

Yes, of course. First deprecate it, then remove. Was just proposing the end result 😄 .
