### ISSUE TITLE
Provide configurable 'too many failed secret retrievals' security alert

### ISSUE THREAD

**Issue by stijnmoreels** [arcus-azure/arcus.security#294]
**Is your feature request related to a problem? Please describe.**
We don't have a limit on the failed attempts of retrieved secrets. Malicious activity can possibly go unnoticed via this way. 

**Describe the solution you'd like**
We should start with maybe adding a (optional) configurable threshold when an security alert is logged. 

**Describe alternatives you've considered**
A throttling threshold can also be considered, but maybe in a later phase.

**Comment by stijnmoreels** [comment]
@fgheysels @pim-simons @gverstraete @meersschautarnaud , thoughts? Is this something we should provide, or should we rely on other/external systems and/or is this too project-specific to be handled by Arcus?

**Comment by pim-simons** [comment]
For me, this feels like something where we should rely on other/external systems to provide this. Azure KeyVault has alerts (https://docs.microsoft.com/en-us/azure/key-vault/general/alert) which allows this kind of monitoring.

**Comment by gverstraete** [comment]
I agree with Pim on this one! It should be up to the resource to tell if we are too agressive, but then we should (from an arcus point of view) look into caching and smart secret refreshing... I would not go into this direction with the package (personal opinion)

**Comment by fgheysels** [comment]
I agree, this does not belong in Arcus.   The responsability to alert on these kind of things, lies with KeyVault imho.

**Comment by stijnmoreels** [comment]
Ok, thx for your input! Let's close this then. We can always come back when some external resource doesn't support this, and/or consumers ask for more telemetry.
