### ISSUE TITLE
Add extra link on secret store index page to 'How to use secret store in Azure Functions'

### ISSUE THREAD

**Issue by fgheysels** [arcus-azure/arcus.security#301]
> We should have some simple documentation on how to use / integrate the ISecretProvider in an Azure Function project.

>I know that we consider the Arcus Templates as documentation / getting started as well, but I think it is not sufficient in this case.
(For instance, people that already have an existing Function who want to make use of the SecretProvider, or if you started a Function project but didn't use the template because you're not going to use a Http trigger (AFAIK, there only exists a template for functions which creates a Function that is triggered via HTTP).

We should add an extra link to the secret store index page for more visibility.

**Comment by stijnmoreels** [comment]
Is written here: https://security.arcus-azure.net/features/secret-store/#using-secret-store-within-azure-functions

Maybe we need to add some extra links to this part.

**Comment by stijnmoreels** [comment]
There also exists an Azure Funtions project template on Databricks, which also uses the secret store, and when we release our new version of Arcus messaging, we will have two new Azure Functions project templates for Queue/Topic subscription triggers.

**Comment by stijnmoreels** [comment]
All change this issue to adding an extra link in the start of the document, to guide users directly to the Azure Functions section.
