### ISSUE TITLE
Remove empty `CacheConfiguration` constructor

### ISSUE THREAD

**Issue by stijnmoreels** [arcus-azure/arcus.security#306]
**Is your feature request related to a problem? Please describe.**
When designing the caching of the secret providers, we extracted this to an `CacheConfiguration` model. The empty constructor had a default of 5min cache duration, but we have made this more explicit with a `.Default` static implementation, making this empty constructor obsolete.

**Describe the solution you'd like**
Remove the empty `CacheConfiguration` constructor.

**Comment by gauravagrwal** [comment]
Hi @stijnmoreels, I was working on this and noticed there are tests which are using empty `CacheConfiguration` constructor in the application, will we be replacing those with mock of `ICacheConfiguration` ?

**Comment by stijnmoreels** [comment]
> Hi @stijnmoreels, I was working on this and noticed there are tests which are using empty `CacheConfiguration` constructor in the application, will we be replacing those with mock of `ICacheConfiguration` ?

Hi! Great enthousiasm! This issue, is actually for the next major, which is still some time away. First will come v1.7. But thanks for your enthousiasm!

To answer the question, normally those tests would only have to be deleted as the default static implementation is and should already be tested.
[This list](https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+user%3Aarcus-azure+label%3A%22good+first+issue%22) all the starter issues for Arcus. Feel free to browse and thanks again for your enthusiasm!🙏

**Comment by stijnmoreels** [comment]
Ps, please check first on issues where you aren't the author if you can get assigned on it, so there's no parallel work being done. 👍
