### ISSUE TITLE
Remove deprecated package `Microsoft.Azure.KeyVault.*` from `Arcus.Security.Providers.AzureKeyVault`

### ISSUE THREAD

**Issue by stijnmoreels** [arcus-azure/arcus.security#311]
**Is your feature request related to a problem? Please describe.**
Currently, we still provide backwards capability to the `Microsoft.Azure.KeyVault` package but this is now made deprecated.

**Describe the solution you'd like**
Remove the package so we solely rely on the `Azure.Security.KeyVaultSecrets` package.

**Comment by stijnmoreels** [comment]
We can make this not a breaking change by implementing (internally) our obsolete `IKeyVaultAuthention` interface and use `TokenCredential` instead. This will act as a kind of 'proxy' between obsolete types and will allow us to remove the deprecated Microsoft packages.

**Comment by stijnmoreels** [comment]
Hmm, this will not work without breaking stuff, bc the `IKeyVaultClient` is used as a `protected` overridable method, which means that this method would be removed if we remove the deprecated pacakges...

**Comment by gverstraete** [comment]
When is this planned...?

There are alternatives now for each package we use I think: https://www.nuget.org/packages/Microsoft.Azure.KeyVault/

**Comment by stijnmoreels** [comment]
> When is this planned...?
> 
> There are alternatives now for each package we use I think: https://www.nuget.org/packages/Microsoft.Azure.KeyVault/

They will be deleted in the next major version, after Observability's major version is released.
