### ISSUE TITLE
Remove the obsolete Azure Key Vault secret store extensions

### ISSUE THREAD

**Issue by stijnmoreels** [arcus-azure/arcus.security#329]
**Is your feature request related to a problem? Please describe.**
When designing the Azure Key Vault secret provider for the secret store, there were a lot of changes and migrations: adding options, different authentication mechanisms, new Azure SDK... The older secret store extensions are still in the source.

**Describe the solution you'd like**
Remove the older obsolete Azure Key Vault secret store extensions.

**Comment by fgheysels** [comment]
I think we should do this, and not wait any longer with it.
All those obsolete methods (some of them are already obsolete for quite some time - for instance the ones that have the `allowCaching` parameter are really polluting the intellisense in Visual Studio.  It will make things cleaner and easier if they're gone.

**Comment by stijnmoreels** [comment]
Yes, was one of the suggestions on observability too, but we didn't go through with it bc that was the only reason why we would have a breaking change.
