### ISSUE TITLE
All project doesn't contain all projects

### ISSUE THREAD

**Issue by stijnmoreels** [arcus-azure/arcus.security#330]
**Is your feature request related to a problem? Please describe.**
Currently, we have an `Arcus.Security.All` package, but this package doesn't contain all the available projects.

**Describe the solution you'd like**
Determine which projects should be included in this `Arcus.Security.All` project. Azure Functions? All secret providers?

**Comment by stijnmoreels** [comment]
We could remove this in v1.7.

**Comment by fgheysels** [comment]
I think we should remove this 'All' project.  
IMHO, it makes no sense to have a package that installs all the security-related assemblies.   Who's going to use KeyVault and Hashicorp, and ..... in a single project ?

Therefore, we should simply remove it.
