### ISSUE TITLE
doc: Improve welcome page

### ISSUE THREAD

**Issue by fgheysels** [arcus-azure/arcus.security#348]
In my opinion, we can improve the documentation of Arcus.Security.

The 'Welcome' page should have an 'Introduction' section which shortly describes what this module is about.

Something like this:

> # Introduction
> Arcus.Security allows you to easily work with secrets.  Instead of retrieving sensitive information from your application's configuration, Arcus.Security allows you to easily retrieve secrets from a configured Secret Store.  Arcus.Security supports multiple secret-stores like Azure KeyVault, Hashicorp, etc... 
> Additionally, Arcus.Security makes sure that retrieved secrets are cached for a while, so that you avoid multiple calls to the backing Secret Store, preventing throttling.

(Maybe some additional things can be added).

Next to that, I would remove the 'Features' section from the welcome page, as we have links to the features in the menu on the left side of the page.

**Comment by stijnmoreels** [comment]
> I would remove the 'Features' section from the welcome page, as we have links to the features in the menu on the left side of the page.

Maybe we can provide a sort of block with 'most used' features or some sort? Currently, we have a 'secret store / What is it?' in our index while this is much more descriptive than the 'secret store integration' in our left page side menu. We could of course consider changing the names of that menu together with removing the feature list on the index page. 👍 

Introduction is also great! 💯

**Comment by fgheysels** [comment]
> Maybe we can provide a sort of block with 'most used' features or some sort? Currently, we have a 'secret store / What is it?' in our index while this is much more descriptive than the 'secret store integration' in our left page side menu. 
I thought that as well, but those 2 things link to the same page
