### ISSUE TITLE
Expose Version of Key Vault Secret in KeyVaultSecretProvider

### ISSUE THREAD

**Issue by SamVanhoutte** [arcus-azure/arcus.security#37]
In the KeyVaultSecretProvider, we return the value of a secret, when found
At the same time, it can be needed to know the version of the secret that was retrieved.

This issue is to track it

**Comment by stijnmoreels** [comment]
This will change the `ISecretProvider`, @tomkerkhove this is probably for later version?

**Comment by tomkerkhove** [comment]
You can already add a new version next to it ;)

**Comment by stijnmoreels** [comment]
I propose creating a new model that has value+version so we don't depend on microsoft models?
@tomkerkhove what is the default approach on Arcus for obsolete functionality: versioned interface + obsolete attribute?

**Comment by tomkerkhove** [comment]
You don't need a versioned interface imo, you can just add the new method next to the current one.

I'm not sure if we should add our own model given people want to have more information about the secret itself as well, but we can start with our own model until there is effective demand for this.

**Comment by stijnmoreels** [comment]
> You don't need a versioned interface imo, you can just add the new method next to the current one.

So you mean that we should allow a breaking change on the next release?

> I'm not sure if we should add our own model given people want to have more information about the secret itself as well, but we can start with our own model until there is effective demand for this.

Ok

**Comment by tomkerkhove** [comment]
I'm saying that we can add the new endpoint to the current interface and mark the old one as obsolete. Before we ship 1.0.0 we'll get rid of that one then.

Feel free to work on this if you want @stijnmoreels and as suggested by you a small custom model is ok.

**Comment by tomkerkhove** [comment]
Done via #58
