### ISSUE TITLE
KeyVault provider GetRawSecretAsync continues without returning value

### ISSUE THREAD

**Issue by Pauwelz** [arcus-azure/arcus.security#407]
**Describe the bug**
When using the GetRawSecretAsync on a secret stored in KeyVault to get a API Key for a Named HTTP Client, the code continues without waiting for the response.

**To Reproduce**
```csharp
ConfigureServices(
  (_, services) => {
    services
      .AddHttpClient(
        "SalesForce",
        async (serviceProvider, client) => {
          var secretProvider =
            serviceProvider.GetRequiredService<ISecretProvider>();

          string baseUrl = await secretProvider.GetRawSecretAsync(
            "SalesForceBaseUri"
          );
          client.BaseAddress = new Uri(baseUrl);

          string key = await secretProvider.GetRawSecretAsync(
            "SalesForce-SubscriptionKey"
          );
          client.DefaultRequestHeaders.Add(
            "Ocp-Apim-Subscription-Key",
            key
          );
        }
      );
  }
)
```

**Expected behavior**
That the secret gets retrieved correctly like it does with a config file.

**Additional context**
Using GetRawSecretAsync on a secret stored in config file or environment works correctly as we can see with the BaseUri
![image](https://user-images.githubusercontent.com/22931593/225878931-3a915754-b7c0-4d37-bcec-b63a5ed04160.png)

Switching to GetRawSecret also works fine (although taking 15 seconds)
![image](https://user-images.githubusercontent.com/22931593/225878800-36c7241e-b1e5-4d49-b188-23beadc099ae.png)

Using Arcus.Security 1.9.0 with .Net 6 and Functions v4 (Isolated)

**Comment by stijnmoreels** [comment]
Usually, when registering services, asynchronous code is not recommended. That is also why we introduced synchronous secret retrieval for the secret store. Could you check if this works for `GetRawSecret` instead?

**Comment by Pauwelz** [comment]
With GetRawSecret it works as expected indeed.
If it's not recommended to to things async during registration then I guess we will switch in our code.

If we use GetRawSecretAsync during the execution of the function, to retrieve the secret, then it works fine as well.

**Comment by stijnmoreels** [comment]
> With GetRawSecret it works as expected indeed.

Ok, that's great! 🥳 Glad we could be of assistance. Thx for contacting, using Arcus, and promoting it, means a lot 😉.

> If it's not recommended to to things async during registration then I guess we will switch in our code.

Something that Microsoft's dependency container is not really build for (unlike StructureMap, for example). So, I would indeed recommend using synchronous stuff there.

> If we use GetRawSecretAsync during the execution of the function, to retrieve the secret, then it works fine as well.

Yes, in those cases, it is really 'async all the way', I guess.
