### ISSUE TITLE
Use generic cache interface instead of IMemoryCache

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.security#49]
Currently we are only accepting `IMemoryCache` for our cached secret provider.

This is fine but this also limits the supported caches to only memory cache avoiding us of using things like distributed cache invalidations.

**Describe the solution you'd like**
Ideally we use a more generic interface that is part of the .NET framework that supports this.

Alternatively we can introduce our own `ICache` but I would like to avoid that.

**Note**
Opening up the supported caches also comes with a risk - Information/secret leakage by storing it in persistent caches outside of the process.

We should strongly discourage this in the documentation as this is a security threat.

Relates to #8

**Comment by stijnmoreels** [comment]
build-in `ObjectCache`?

**Comment by tomkerkhove** [comment]
As far as I know that's no longer in .NET Core

**Comment by stijnmoreels** [comment]
Ah, yes. Just create our own with `IDisposable` as parent then?

**Comment by tomkerkhove** [comment]
That's the exercise we want to do here - Is there an alternative to use or do we build our own which we prefer to avoid as the framework has a ton of providers out of the box.

**Comment by fgheysels** [comment]
What other caches are you thinking about ?
I mean, you definitely do not want to cache items out of process or have secrets persisted somewhere as you've mentionned yourself already.   So, I wonder what would be the gain of having other cache-implementations.

Regarding the distributed cache-invalidation: I was just wondering if KeyVault is not able to trigger an event when a secret is updated.  If that would be the case, the `KeyVaultSecretProvider` could subscribe on these events and invalidate the relevant cached items.

**Comment by tomkerkhove** [comment]
Event is a approach but that would mean that it exposes an HTTP endpoint to receive events on which is not what I would want as a consumer.

The only other cache that I would support is to have distributed eviction, all other ones are out of question. But that would mean we can use our own interface maybe?

**Comment by tomkerkhove** [comment]
Now that I think of it again, we can just create a "distributed memory cache" that also implements `IMemoryCache`. Think this would make the most sense and a clear signal to consumers.

Thoughts?

**Comment by fgheysels** [comment]
> Event is a approach but that would mean that it exposes an HTTP endpoint to receive events on which is not what I would want as a consumer.
> 
> The only other cache that I would support is to have distributed eviction, all other ones are out of question. But that would mean we can use our own interface maybe?

I was more thinking of the usage of eventgrid for that, but then we'd need [this](https://feedback.azure.com/forums/909934-azure-event-grid/suggestions/36207106-allow-keyvault-to-emit-events-using-event-grid-whe).

**Comment by tomkerkhove** [comment]
> > Event is a approach but that would mean that it exposes an HTTP endpoint to receive events on which is not what I would want as a consumer.
> > The only other cache that I would support is to have distributed eviction, all other ones are out of question. But that would mean we can use our own interface maybe?
> 
> I was more thinking of the usage of eventgrid for that, but then we'd need [this](https://feedback.azure.com/forums/909934-azure-event-grid/suggestions/36207106-allow-keyvault-to-emit-events-using-event-grid-whe).

That is correct, but in order to consume those events on Event Grid our `KeyVaultSecretProvider` needs to expose an HTTP endpoint which can receive those events.

**Comment by tomkerkhove** [comment]
> Now that I think of it again, we can just create a "distributed memory cache" that also implements `IMemoryCache`. Think this would make the most sense and a clear signal to consumers.
> 
> Thoughts?

I think this should work and we can keep on using this one.

Any objections @SamVanhoutte 	@stijnmoreels 	@fgheysels 	?

**Comment by tomkerkhove** [comment]
No objections so closing this one as we'll stick with it for now, people can still extend it to build a memory cache with distributed inviction if they want.
