### ISSUE TITLE
Provide integration test for Managed Service Identity authentication

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.security#60]
Provide integration test for Managed Service Identity authentication, if possible.

This depends on the Azure Infrastructure but if I'm not mistaken this can also be "hacked" via an environment variable or this approach - https://stackoverflow.com/questions/47756248/how-to-use-msi-for-development-in-visual-studio

We need to see if this works both locally & CI + if we need docs on running the tests locally.

**Comment by stijnmoreels** [comment]
### Environment variable
Should we first have the `TenantId` and `Thumbprint/Password` of the service principle that is now used in the integration test.

> Set an environment variable named **AzureServicesAuthConnectionString** to **RunAs=App;AppId=AppId;TenantId=TenantId;CertificateThumbprint=Thumbprint;CertificateStoreLocation=CurrentUser**. You need to replace **AppId**, **TenantId**, and **Thumbprint** with actual values or set an environment variable named **AzureServicesAuthConnectionString** to **RunAs=App;AppId=AppId;TenantId=TenantId;AppKey=Secret**. You need to replace **AppId**, **TenantId**, and **Secret** with actual values.

**Comment by tomkerkhove** [comment]
I can provide that if you want, shall I create a variable group for those?

**Comment by tomkerkhove** [comment]
Or prefer to have them raw?

**Comment by stijnmoreels** [comment]
> I can provide that if you want, shall I create a variable group for those?

There already exists a variable group for the integration test suite of the Arcus.Security repo; so I would suggest that these are added there?

**Comment by tomkerkhove** [comment]
I've introduced `Arcus_MSI_AzureServicesAuth_ConnectionString` in that variable group which should be giving you what you need.

Basically it's just the following:
> RunAs=App;AppId=$(Arcus_ServicePrincipal_ApplicationId);TenantId=$(Arcus_Tenant);AppKey=$(Arcus_ServicePrincipal_AccessKey)

Does that provide you with all you need?
