### ISSUE TITLE
Document how to run integration tests

### ISSUE THREAD

**Issue by stijnmoreels** [arcus-azure/arcus.security#66]
The Event Grid repository has an introduction on how to run the integration tests present in the repo. This repository hasn't got any such introduction.

Could be reasonable to add this here as well. There are also other environment variables that needs to be configured.

**Comment by tomkerkhove** [comment]
I presume you are referring to https://github.com/arcus-azure/arcus.eventgrid#how-do-i-run-the-integration-tests, is that correct?

If so, good idea but I'd suggest moving it to a file on `guides/running-integration-tests.md` which is referred to in the README to keep it clean. What do you think?

Ok if I assign this to you?

**Comment by stijnmoreels** [comment]
> I presume you are referring to https://github.com/arcus-azure/arcus.eventgrid#how-do-i-run-the-integration-tests, is that correct?

Yes, you are :)

> Ok if I assign this to you?

Well, not entirely sure if I know enough to do this. The setup of Key Vault, the authentication choice to use, registering of applications to gain access to Key Vault, ... and then the ARM template I presume (?) that needs to be included in the guide.

**Comment by tomkerkhove** [comment]
The ARM template is available here: https://github.com/arcus-azure/arcus.security/blob/master/deploy/arm/azuredeploy.json

Tests are using username/password approach as you can find here: https://github.com/arcus-azure/arcus.security/blob/master/src/Arcus.Security.Tests.Integration/appsettings.json

But our docs should just mention that an Azure AD App is required to be created and use app id & secret, ARM template should handle the rest!
