### ISSUE TITLE
Provide capability to retrieve a secret from Azure Key Vault

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.security#7]
Provide capability to retrieve a secret.

In the first version, we should only support basic authentication.

We should provide an `AzureKeyVaultProvider` that implements `ISecretProvider` (#20) which is reading secrets from Azure Key Vault.

This should end up in the `Arcus.Security.AzureKeyVault` 📦 .

**Comment by stijnmoreels** [comment]
This seems like the first required and useful feature. This and #22 can be assigned to me if you like. 

Maybe we have to have a chat on the specs or are they have to be specified in here (not sure how big this is, hence my question).

**Comment by tomkerkhove** [comment]
We'll need to keep in mind that we will have different flavors of authentication so we should abstract that concept out via an interface or something related.

See #10 & #11

**Comment by SamVanhoutte** [comment]
The Authentication should indeed make abstraction of the actual implementation (we can inject the right SecretProvider).  
I just wonder what's the best approach to configure the different key providers (KeyVault will have different config values than others, for example)

**Comment by tomkerkhove** [comment]
Can you provide docs for this please @SamVanhoutte?
