### ISSUE TITLE
Support AzureServiceTokenProvider constructor optional parameters

### ISSUE THREAD

**Issue by BlackstarSolar** [arcus-azure/arcus.security#89]
While setting the `AzureServiceTokenProvider` connection string via the _AzureServicesAuthConnectionString_ environment variable works in many cases, in some cases (e.g. Azure App Service configuration) building a connection string, as an environment variable, often from other environment variables isn't practical/possible.

Additionally specifying the `azureAdInstance` parameter (for when not running in Azure public cloud) via environment variable is not currently supported.

Supporting the optional `connectionString` and `azureAdInstance` parameters would provide greater flexibility.

**Comment by tomkerkhove** [comment]
That's a good suggestion, thanks!

@stijnmoreels 	This might help you with the issues you are suffering from now as well.

**Comment by tomkerkhove** [comment]
Thank you @BlackstarSolar 	!
