### ISSUE TITLE
Provide resiliency for service-side throttling for Azure Key Vault

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.security#9]
Provide resiliency for service-side throttling by retrying `HTTP 429 TOO MANY REQUESTS`.

**Describe the solution you'd like**
These should be handled according by using Polly based on the recommended guidance documented [here](https://docs.microsoft.com/en-us/azure/key-vault/key-vault-ovw-throttling#recommended-client-side-throttling-method).

**Comment by stijnmoreels** [comment]
Should this be configurable by external users or is this just an internal improvement for the `KeyVaultClient`?

**Comment by stijnmoreels** [comment]
Yeah, I'll do this.
Seems fun!

**Comment by tomkerkhove** [comment]
For now it's ok to have the fixed retry that is part of your PR, if people want to have control over it we can add it later on.
