### ISSUE TITLE
ISecretProvider documentation is outdated

### ISSUE THREAD

**Issue by fgheysels** [arcus-azure/arcus.security#93]
**Describe the bug**
The code sample in the [documentation page](https://security.arcus-azure.net/features/key-vault/extensions/iconfiguration-integration) refers to an obsolete constructor.

**To Reproduce**
When using the code from the documentation, you'll get a warning that says that the constructor for `KeyVaultSecretProvider` is obsolete:

```csharp
var vaultAuthenticator = new ManagedServiceIdentityAuthenticator();
var vaultConfiguration = new KeyVaultConfiguration(keyVaultBaseUrl);
var yourSecretProvider = new KeyVaultSecretProvider(vaultAuthenticator, vaultConfiguration);
```

>The call is ambiguous between the following methods or properties: 'KeyVaultSecretProvider.KeyVaultSecretProvider(IKeyVaultAuthenticator, IKeyVaultConfiguration)' and 'KeyVaultSecretProvider.KeyVaultSecretProvider(IKeyVaultAuthentication, IKeyVaultConfiguration)'	

**Expected behavior**
Reference documentation that uses the latest version of the library :)

**Additional context**
 - Version: 0.4.0

**Comment by tomkerkhove** [comment]
Clarified in #96, thank you!
